import {useState} from 'react';

import Col from 'react-bootstrap/Col';
import Container from 'react-bootstrap/Container';
import Form from 'react-bootstrap/Form';
import Row from 'react-bootstrap/Row';
import Table from 'react-bootstrap/Table';

function Opgave8() {
	// const words = require('an-array-of-english-words');
	const vowels = ['A', 'E', 'I', 'O', 'U'];
	const consonants = ['B', 'C', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z'];
	const LyricsAuth = require('lyrics-search');
	const lyricsAuth = new LyricsAuth();


	const patterns = [
		'AIEO AIEO AIEO IAO',
		'A A A I EE',
		'A A A I EE A A U',
		'A A A I EE A A A I EE A A U',
		'OEE UI O E AE A OI EE AE',
		'O I I O I I OU EE EE',
		'O OI I OA AY IE I'
	];

	const patternsNoSpaces = [
		'AIEOAIEOAIEOIAO',
		'AAAIEEAAU',
		'AAAIEEAAAIEEAAU',
		'OEEUIOEAEAOIEEAE',
		'OIIOIIOUEEEE',
		'OOIIOAAYIEI'
	];

	const songs = [
		['Queen', 'Bohemian Rhapsody'],
		['Danny Vera', 'Roller Coaster'],
		['Eagles', 'Hotel California'],
		['Billy Joel', 'Piano Man'],
		['Coldplay', 'Fix You'],
		['Led Zeppelin', 'Stairway To Heaven'],
		['Pearl Jam', 'Black'],
		['Boudewijn de Groot', 'Avond'],
		['Metallica', 'Nothing Else Matters '],
		['Queen', 'Love Of My Life'],
		['Pink Floyd', 'Wish You Were Here'],
		['Dire Straits', 'Brothers In Arms '],
		['Golden Earring', 'Radar Love '],
		['Pink Floyd', 'Comfortably Numb '],
		['Guns N Roses', 'November Rain'],
		['Disturbed', 'The Sound Of Silence'],
		['Deep Purple', 'Child In Time '],
		['DI-RECT', 'Soldier On'],
		['Prince', 'Purple Rain '],
		['Dire Straits', 'Sultans Of Swing'],
		['Toto', 'Africa '],
		['Coldplay', 'Viva La Vida'],
		['Bruce Springsteen', 'The River'],
		['David Bowie', 'Heroes '],
		['Pink Floyd', 'Shine On You Crazy Diamond (Pts. 1-5)'],
		['Metallica', 'One '],
		['Dire Straits', 'Telegraph Road '],
		['AC/DC', 'Thunderstruck'],
		['Meat Loaf', 'Paradise By The Dashboard Light '],
		['The Cure', 'A Forest'],
		['Racoon', 'Oceaan'],
		['Metallica', 'Master Of Puppets'],
		['John Lennon', 'Imagine'],
		['Rage Against The Machine', 'Killing In The Name'],
		['Nirvana', 'Smells Like Teen Spirit'],
		['Pearl Jam', 'Just Breathe'],
		['Simon & Garfunkel', 'The Sound Of Silence'],
		['ABBA', 'Dancing Queen'],
		['Fleetwood Mac', 'Go Your Own Way'],
		['Guns N Roses', 'Sweet Child O Mine '],
		['Klein Orkest', 'Over De Muur'],
		['Procol Harum', 'A Whiter Shade Of Pale'],
		['Lady Gaga  Bradley Cooper', 'Shallow'],
		['Linkin Park', 'In The End'],
		['Fleetwood Mac', 'The Chain'],
		['Michael Kiwanuka', 'Cold Little Heart '],
		['George Michael  Queen', 'Somebody To Love (Live)'],
		['Queen', 'Innuendo'],
		['Metallica', 'Enter Sandman'],
		['Radiohead', 'Creep'],
		['Miss Montreal', 'Door De Wind'],
		['Phil Collins', 'In The Air Tonight '],
		['Eminem', 'Lose Yourself'],
		['Johnny Cash', 'Hurt'],
		['Wim Sonneveld', 'Het Dorp'],
		['Coldplay', 'Yellow'],
		['Supertramp', 'School'],
		['Nothing But Thieves', 'Impossible (Orchestral Version Live at Abbey Road)'],
		['Robbie Williams', 'Angels'],
		['The Beach Boys', 'God Only Knows'],
		['Coldplay', 'The Scientist '],
		['Queen  David Bowie', 'Under Pressure'],
		['U2', 'With Or Without You'],
		['Paolo Nutini', 'Iron Sky '],
		['The Rolling Stones', 'Paint It Black'],
		['Stef Bos', 'Papa'],
		['Tom Odell', 'Another Love'],
		['Coldplay  Avicii', 'A Sky Full Of Stars'],
		['U2', 'Sunday Bloody Sunday'],
		['Supertramp', 'Fools Overture'],
		['Neil Diamond', 'Sweet Caroline'],
		['Volbeat', 'Lola Montez'],
		['Muse', 'Uprising'],
		['Pearl Jam', 'Alive'],
		['Amy Winehouse', 'Back To Black'],
		['Guus Meeuwis', 'Brabant'],
		['Acda  De Munnik', 'Het Regent Zonnestralen'],
		['Simon  Garfunkel', 'Bridge Over Troubled Water'],
		['The Rolling Stones', 'Sympathy For The Devil'],
		['Cranberries', 'Zombie'],
		['Electric Light Orchestra', 'Mr. Blue Sky'],
		['Son Mieux', 'Multicolor'],
		['Coldplay', 'Clocks '],
		['AC/DC', 'Highway To Hell'],
		['The Alan Parsons Project', 'Old And Wise'],
		['The Beatles', 'Let It Be'],
		['Queen', 'Somebody To Love'],
		['Queen', 'Dont Stop Me Now'],
		['Pink Floyd', 'Another Brick In The Wall'],
		['Kensington', 'Sorry'],
		['The Beatles', 'Here Comes The Sun'],
		['Elvis Presley', 'Suspicious Minds'],
		['Dolly Parton', 'Jolene'],
		['Goldband', 'Noodgeval'],
		['Queen', 'Who Wants To Live Forever'],
		['Liesbeth List  Ramses Shaffy', 'Pastorale'],
		['Dire Straits', 'Private Investigations '],
		['Sinéad OConnor', 'Nothing Compares 2 U'],
		['Floor Jansen  Henk Poort', 'Phantom Of The Opera'],
		['U2', 'One'],
		['Red Hot Chili Peppers', 'Under The Bridge'],
		// ['Sinéad OConnor', 'Troy'],
		// ['The Doors', 'Riders On The Storm '],
		// ['Depeche Mode', 'Enjoy The Silence'],
		// ['Journey', 'Dont Stop Believin'],
		// ['The Rolling Stones', 'Gimme Shelter'],
		// ['Snow Patrol', 'Chasing Cars'],
		// ['Simple Minds', 'Belfast Child'],
		// ['Rammstein', 'Deutschland'],
		// ['Kate Bush', 'Wuthering Heights'],
		// ['Fleetwood Mac', 'Dreams'],
		// ['AC/DC', 'Whole Lotta Rosie'],
		// ['Kate Bush', 'Running Up That Hill '],
		// ['Rammstein', 'Du Hast'],
		// ['Harry Styles', 'Sign Of The Times'],
		// ['The Killers', 'Mr. Brightside'],
		// ['George Michael', 'Careless Whisper'],
		// ['Creedence Clearwater Revival', 'Have You Ever Seen The Rain'],
		// ['The Rolling Stones', 'Angie'],
		// ['The Verve', 'Bitter Sweet Symphony '],
		// ['Sting', 'Fields Of Gold'],
		// ['Golden Earring', 'When The Lady Smiles '],
		// ['Muse', 'Knights Of Cydonia '],
		// ['R.E.M.', 'Losing My Religion'],
		// ['Rammstein', 'Sonne'],
		// ['The Beatles', 'Blackbird'],
		// ['Black Sabbath', 'Paranoid'],
		// ['U2', 'Where The Streets Have No Name'],
		// ['Foo Fighters', 'The Pretender'],
		// ['ABBA', 'The Winner Takes It All'],
		// ['Claudia de Breij', 'Mag Ik Dan Bij Jou'],
		// ['BLØF ft. Geike', 'Zoutelande'],
		// ['Queen', 'The Show Must Go On'],
		// ['David Bowie', 'Space Oddity '],
		// ['Eric Clapton', 'Tears In Heaven'],
		// ['The Beatles', 'Hey Jude'],
		// ['Dire Straits', 'Money For Nothing '],
		// ['Van Dik Hout', 'Stil In Mij'],
		// ['Oasis', 'Dont Look Back In Anger'],
		// ['Sting', 'Fragile'],
		// ['Anouk', 'Nobodys Wife'],
		// ['Ike  Tina Turner', 'Proud Mary'],
		// ['Otis Redding', '(Sittin On) The Dock Of The Bay'],
		// ['U2', 'I Still Havent Found What Im Looking For'],
		// ['Bankzitters', 'Je Blik Richting Mij'],
		// ['Keane', 'Somewhere Only We Know'],
		// ['Bankzitters', 'Stapelgek'],
		// ['Michael Jackson', 'Billie Jean'],
		// ['De Jeugd Van Tegenwoordig', 'Sterrenstof'],
		// ['Elton John', 'Your Song'],
		// ['Jason Paige', 'Gotta Catch Em All (Pokemon Theme Song)'],
		// ['Animals', 'House Of The Rising Sun'],
		// ['André Hazes', 'Kleine Jongen'],
		// ['Red Hot Chili Peppers', 'Californication'],
		// ['The Moody Blues', 'Nights In White Satin'],
		// ['Barbara Pravi', 'Voilà'],
		// ['Billy Joel', 'Goodnight Saigon'],
		// ['The Beatles', 'Yesterday'],
		// ['Aerosmith', 'Dream On'],
		// ['Falco', 'Jeanny'],
		// ['Iron Maiden', 'Fear Of The Dark (Live)'],
		// ['Goo Goo Dolls', 'Iris'],
		// ['Foo Fighters', 'Everlong'],
		// ['Nirvana', 'Come As You Are'],
		// ['Within Temptation', 'Ice Queen '],
		// ['Oasis', 'Wonderwall'],
		// ['Ramses Shaffy', 'Laat Me'],
		// ['Bruce Springsteen', 'Streets Of Philadelphia'],
		// ['Kensington', 'Uncharted'],
		// ['System Of A Down', 'Chop Suey!'],
		// ['Bryan Adams', 'Summer Of 69'],
		// ['Chris Stapleton', 'Tennessee Whiskey'],
		// ['ABBA', 'Gimme Gimme Gimme'],
		// ['Leonard Cohen', 'Hallelujah'],
		// ['Elvis Presley', 'In The Ghetto'],
		// ['Nick Cave  The Bad Seeds', 'Into My Arms'],
		// ['Taylor Swift', 'All Too Well (10 Minute Version)'],
		// ['Tracy Chapman', 'Fast Car'],
		// ['De Dijk', 'Niemand In De Stad'],
		// ['Maan x Goldband', 'Stiekem'],
		// ['Eagles', 'The Last Resort '],
		// ['Bon Jovi', 'Bed Of Roses '],
		// ['Michael Jackson', 'Earth Song'],
		// ['Simple Minds', 'Dont You (Forget About Me)'],
		// ['Adele', 'Someone Like You'],
		// ['Dire Straits', 'Walk Of Life'],
		// ['Creedence Clearwater Revival', 'Fortunate Son'],
		// ['Bob Marley  The Wailers', 'Three Little Birds'],
		// ['Faithless', 'Insomnia '],
		// ['Queen', 'Killer Queen'],
		// ['John Miles', 'Music'],
		// ['Guns N Roses', 'Paradise City '],
		// ['Earth, Wind  Fire', 'September'],
		// ['George Michael  Elton John', 'Dont Let The Sun Go Down On Me'],
		// ['The Weeknd', 'Blinding Lights'],
		// ['Harry Styles', 'As It Was'],
		// ['Bruce Springsteen', 'Dancing In The Dark'],
		// ['Marillion', 'Kayleigh'],
		// ['ABBA', 'Lay All Your Love On Me'],
		// ['De Dijk', 'Dansen Op De Vulkaan'],
		// ['Herman Brood  His Wild Romance', 'Saturday Night'],
		// ['Ramses Shaffy', 'Zing, Vecht, Huil, Bid, Lach, Werk En Bewonder'],
		// ['Adele', 'Rolling In The Deep'],
		// ['Mary J. Blige  U2', 'One'],
		// ['Bankzitters', 'Is Dat Nou Echt?'],
		// ['Deep Purple', 'Smoke On The Water '],
		// ['Linkin Park', 'Numb'],
		// ['Sting', 'Englishman In New York'],
		// ['Radiohead', 'Street Spirit (Fade Out)'],
		// ['The Cult', 'She Sells Sanctuary'],
		// ['Kenny Rogers  Dolly Parton', 'Islands In The Stream'],
		// ['Helene Fischer', 'Atemlos Durch Die Nacht'],
		// ['Son Mieux', 'Tonight'],
		// ['André Hazes', 'Bloed, Zweet En Tranen'],
		// ['Taylor Swift', 'Anti-Hero'],
		// ['Fleetwood Mac', 'Songbird'],
		// ['U2', 'The Unforgettable Fire'],
		// ['Metallica', 'The Unforgiven '],
		// ['Queens Of The Stone Age', 'No One Knows'],
		// ['The Beatles', 'While My Guitar Gently Weeps'],
		// ['Queen', 'I Want To Break Free'],
		// ['Michael Jackson', 'Thriller '],
		// ['Ed Sheeran', 'Perfect'],
		// ['Lou Reed', 'Perfect Day'],
		// ['Simon  Garfunkel', 'The Boxer'],
		// ['Eminem  Dido', 'Stan '],
		// ['Pink Floyd', 'Echoes'],
		// ['Golden Earring', 'Twilight Zone '],
		// ['Lady Gaga', 'Always Remember Us This Way'],
		// ['Pearl Jam', 'Jeremy'],
		// ['Fleetwood Mac', 'Landslide'],
		// ['Eagles', 'Desperado'],
		// ['Kyteman', 'Sorry'],
		// ['Rammstein', 'Engel'],
		// ['Tears For Fears', 'Everybody Wants To Rule The World'],
		// ['Nothing But Thieves', 'Amsterdam'],
		// ['Lynyrd Skynyrd', 'Free Bird '],
		// ['Metallica', 'Fade To Black'],
		// ['Frank Boeijen Groep', 'Kronenburg Park'],
		// ['R.E.M.', 'Everybody Hurts'],
		// ['Scorpions', 'Wind Of Change'],
		// ['Fleetwood Mac', 'Everywhere'],
		// ['Marco Schuitmaker', 'Engelbewaarder'],
		// ['The Amazing Stroopwafels', 'Oude Maasweg'],
		// ['Jefferson Airplane', 'White Rabbit'],
		// ['Golden Earring', 'Another 45 Miles (Naked)'],
		// ['Slayer', 'Angel Of Death'],
		// ['Editors', 'Papillon'],
		// ['Stromae', 'Lenfer'],
		// ['ABBA', 'Chiquitita'],
		// ['Racoon', 'Love You More'],
		// ['The Pogues  Kirsty MacColl', 'Fairytale Of New York'],
		// ['Arctic Monkeys', 'Do I Wanna Know?'],
		// ['U2', 'Bad'],
		// ['Stromae', 'Formidable'],
		// ['Elton John', 'Rocket Man'],
		// ['Wham!', 'Last Christmas'],
		// ['Evanescence', 'My Immortal'],
		// ['Led Zeppelin', 'Whole Lotta Love '],
		// ['De Dijk', 'Als Ze Er Niet Is'],
		// ['The Scene', 'Iedereen Is Van De Wereld'],
		// ['Kate Bush', 'The Man With The Child In His Eyes'],
		// ['Lana Del Rey', 'Video Games'],
		// ['Fleetwood Mac', 'Sara '],
		// ['Elton John', 'Im Still Standing'],
		// ['Metallica', 'Whiskey In The Jar'],
		// ['Green Day', 'Boulevard Of Broken Dreams'],
		// ['Rowwen Hèze', 'November'],
		// ['Radiohead', 'Karma Police'],
		// ['Danny Vera  Krezip', 'Make It A Memory'],
		// ['Krezip', 'I Would Stay'],
		// ['Bruce Springsteen', 'Born To Run'],
		// ['Proclaimers', 'Im Gonna Be (500 Miles)'],
		// ['Alphaville', 'Forever Young'],
		// ['Normaal', 'Deurdonderen (Live)'],
		// ['Freddie Mercury  Montserrat Caballé', 'Barcelona'],
		// ['Eddie Vedder', 'Society'],
		// ['Motörhead', 'Ace Of Spades'],
		// ['Bruce Springsteen', 'Im On Fire'],
		// ['Jaap Reesema', 'Grijs'],
		// ['The Mamas  The Papas', 'California Dreamin'],
		// ['Live', 'Lightning Crashes'],
		// ['Beth Hart', 'Leave The Light On'],
		// ['David Bowie', 'Starman'],
		// ['DI-RECT', 'Through The Looking Glass'],
		// ['Volbeat', 'Sad Mans Tongue'],
		// ['Iron Maiden', 'Run To The Hills'],
		// ['Bette Midler', 'The Rose'],
		// ['Nightwish', 'Ghost Love Score (Live@Wacken 2013)'],
		// ['Kansas', 'Dust In The Wind'],
		// ['Gary Moore', 'Still Got The Blues '],
		// ['Adele', 'Set Fire To The Rain'],
		// ['Frans Halsema', 'Voor Haar'],
		// ['Adele', 'Skyfall'],
		// ['Faithless', 'God Is A DJ'],
		// ['Peter Gabriel  Kate Bush', 'Dont Give Up'],
		// ['U2', 'Beautiful Day'],
		// ['U2', 'Pride (In The Name Of Love)'],
		// ['Led Zeppelin', 'Kashmir'],
		// ['Frank Boeijen Groep', 'Zeg Me Dat Het Niet Zo Is'],
		// ['Guns N Roses', 'Knockin On Heavens Door'],
		// ['Muse', 'Psycho'],
		// ['Bon Jovi', 'Livin On A Prayer'],
		// ['Queensrÿche', 'Silent Lucidity'],
		// ['Creedence Clearwater Revival', 'Bad Moon Rising'],
		// ['Meat Loaf', 'Bat Out Of Hell '],
		// ['KISS', 'I Was Made For Lovin You'],
		// ['Don McLean', 'Vincent'],
		// ['Kayak', 'Ruthless Queen'],
		// ['ABBA', 'The Day Before You Came'],
		// ['Skik', 'Op Fietse'],
		// ['Queen', 'Radio Ga Ga'],
		// ['Meau', 'Dat Heb Jij Gedaan'],
		// ['ABBA', 'Mamma Mia'],
		// ['Elvis Presley', 'Cant Help Falling In Love'],
		// ['The Police', 'Every Breath You Take'],
		// ['Hozier', 'Take Me To Church'],
		// ['Peter Fox', 'Haus Am See'],
		// ['Creedence Clearwater Revival', 'I Put A Spell On You'],
		// ['BLØF', 'Harder Dan Ik Hebben Kan'],
		// ['Nena', '99 Luftballons'],
		// ['Elbow', 'One Day Like This'],
		// ['Boudewijn de Groot', 'Testament'],
		// ['Nirvana', 'Lithium'],
		// ['Underworld', 'Born Slippy'],
		// ['Tina Turner  David Bowie', 'Tonight (Live)'],
		// ['Jeff Buckley', 'Hallelujah '],
		// ['Doe Maar', 'Sinds 1 Dag Of 2 (32 Jaar)'],
		// ['Toto', 'Hold The Line'],
		// ['Pink Floyd', 'Time'],
		// ['A-Ha', 'Take On Me'],
		// ['Elvis Presley', 'My Boy'],
		// ['The Police', 'Roxanne'],
		// ['Billy Joel', 'Shes Always A Woman'],
		// ['Elvis Presley', 'Always On My Mind'],
		// ['Johnny Cash', 'Ring Of Fire'],
		// ['Peter Maffay', 'Du'],
		// ['ABBA', 'Eagle '],
		// ['The Scene', 'Blauw'],
		// ['Phil Collins', 'Against All Odds (Take A Look At Me Now)'],
		// ['Cuby  the Blizzards', 'Window Of My Eyes'],
		// ['Neil Young', 'Heart Of Gold'],
		// ['Frank Sinatra', 'My Way'],
		// ['George Michael', 'Jesus To A Child'],
		// ['Nothing But Thieves', 'Sorry'],
		// ['Avicii ft. Aloe Blacc', 'Wake Me Up'],
		// ['Jacques Brel', 'Ne Me Quitte Pas'],
		// ['Michael Jackson', 'Man In The Mirror'],
		// ['Guns N Roses', 'Welcome To The Jungle'],
		// ['The Rolling Stones', 'You Cant Always Get What You Want '],
		// ['Dire Straits', 'Romeo And Juliet '],
		// ['Rowwen Hèze', 'De Peel In Brand'],
		// ['Abel', 'Onderweg'],
		// ['Supertramp', 'The Logical Song'],
		// ['Queen', 'We Will Rock You'],
		// ['Nirvana', 'The Man Who Sold The World (unplugged)'],
		// ['Phil Collins', 'Another Day In Paradise'],
		// ['Jimi Hendrix', 'All Along The Watchtower'],
		// ['ABBA', 'Thank You For The Music'],
		// ['Charles Aznavour', 'She'],
		// ['Rammstein', 'Zeit'],
		// ['John Denver', 'Take Me Home, Country Roads'],
		// ['Michel Fugain', 'Une Belle Histoire'],
		// ['Charles Aznavour', 'La Bohème'],
		// ['Peter Gabriel', 'Solsbury Hill'],
		// ['Within Temptation', 'Mother Earth'],
		// ['Coldplay', 'Paradise '],
		// ['Bruce Springsteen', 'Tougher Than The Rest'],
		// ['DJ Paul Elstak', 'Rainbow In The Sky'],
		// ['BLØF  Counting Crows', 'Holiday In Spain'],
		// ['Normaal', 'Oerend Hard'],
		// ['Soundgarden', 'Black Hole Sun'],
		// ['Diggy Dex ft. JW Roy', 'Treur Niet (Ode Aan Het Leven)'],
		// ['Chris Isaak', 'Wicked Game '],
		// ['Paul Simon', 'Graceland '],
		// ['Boston', 'More Than A Feeling '],
		// ['Genesis', 'Mama '],
		// ['André Hazes', 'Zij Gelooft In Mij (2004)'],
		// ['ABBA', 'Waterloo'],
		// ['André Hazes', 'De Vlieger'],
		// ['Arctic Monkeys', '505'],
		// ['Michael Jackson', 'Beat It'],
		// ['Jackson Browne', 'The Load Out/Stay '],
		// ['Ede Staal', 'Het Het Nog Nooit Zo Donker West'],
		// ['Mark  Clark Band', 'Worn Down Piano'],
		// ['Jay-Z  Alicia Keys', 'Empire State Of Mind'],
		// ['Adele', 'Make You Feel My Love'],
		// ['Cranberries', 'Linger'],
		// ['Acda  De Munnik', 'Lopen Tot De Zon Komt'],
		// ['Fleetwood Mac', 'Little Lies'],
		// ['Janis Joplin', 'Me And Bobby McGee'],
		// ['Tina Turner', 'The Best'],
		// ['Alice Cooper', 'Poison'],
		// ['Bob Dylan', 'Hurricane '],
		// ['AC/DC', 'Back In Black'],
		// ['Green Day', 'Basket Case'],
		// ['Marco Borsato', 'Dochters'],
		// ['Metallica', 'Sad But True'],
		// ['ABBA', 'Does Your Mother Know?'],
		// ['3 Doors Down', 'Kryptonite'],
		// ['Coolio', 'Gangstas Paradise'],
		// ['The Beatles', 'A Day In The Life'],
		// ['Bruce Springsteen', 'My Hometown'],
		// ['The Who', 'Baba ORiley'],
		// ['BLØF', 'Zo Stil'],
		// ['Stef Bos', 'Is Dit Nu Later'],
		// ['Ike  Tina Turner', 'River Deep Mountain High'],
		// ['Toto', 'Stop Loving You'],
		// ['De Dijk', 'Mag Het Licht Uit'],
		// ['Queen', 'These Are The Days Of Our Lives'],
		// ['The Alan Parsons Project', 'Eye In The Sky '],
		// ['Racoon', 'Het Is Al Laat Toch'],
		// ['Mumford  Sons', 'Little Lion Man'],
		// ['Elvis Presley', 'If I Can Dream'],
		// ['Taylor Swift', 'Cardigan'],
		// ['Guns N Roses', 'Estranged'],
		// ['André Hazes', 'Zeg Maar Niets Meer'],
		// ['Boudewijn de Groot', 'Verdronken Vlinder'],
		// ['Snow Patrol', 'Run'],
		// ['Duncan Laurence', 'Arcade'],
		// ['Andrea Bocelli  Giorgia', 'Vivo Per Lei'],
		// ['Lewis Capaldi', 'Someone You Loved'],
		// ['Pearl Jam', 'Even Flow'],
		// ['The Rolling Stones', '(I Cant Get No) Satisfaction'],
		// ['Alderliefste  Ramses Shaffy', 'Laat Me/Vivre'],
		// ['Pink Floyd', 'The Great Gig In The Sky'],
		// ['Waterboys', 'The Whole Of The Moon '],
		// ['Tina Turner', 'Private Dancer'],
		// ['Suzan  Freek', 'Als Het Avond Is'],
		// ['André Hazes', 'Geef Mij Je Angst'],
		// ['Adele', 'Hello'],
		// ['Måneskin', 'The Loneliest'],
		// ['Pink Floyd', 'Money '],
		// ['Foreigner', 'I Want To Know What Love Is'],
		// ['Rob de Nijs', 'Foto Van Vroeger'],
		// ['Eagles', 'One Of These Nights'],
		// ['ZZ Top', 'La Grange'],
		// ['White Stripes', 'Seven Nation Army'],
		// ['Suzan  Freek', 'Goud'],
		// ['BLØF', 'Omarm'],
		// ['The Beatles', 'Eleanor Rigby'],
		// ['Bill Withers', 'Aint No Sunshine'],
		// ['John Denver', 'Annies Song'],
		// ['Bruce Springsteen', 'Born In The U.S.A.'],
		// ['Eurythmics', 'Sweet Dreams (Are Made Of This)'],
		// ['Ultravox', 'Vienna'],
		// ['Rob de Nijs', 'Het Werd Zomer'],
		// ['Eagles', 'Take It Easy'],
		// ['Mark Ronson ft. Amy Winehouse', 'Valerie'],
		// ['Taylor Swift', 'Love Story (Taylors Version)'],
		// ['Suzan  Freek  Snelle', 'De Overkant'],
		// ['Bonnie Tyler', 'Total Eclipse Of The Heart'],
		// ['Radiohead', 'Paranoid Android'],
		// ['BLØF', 'Aan De Kust (Live)'],
		// ['De Dijk', 'Groot Hart'],
		// ['Doe Maar', 'Belle Hélène'],
		// ['Meat Loaf', 'Id Do Anything For Love (But I Wont Do That)'],
		// ['BLØF', 'Liefs Uit Londen'],
		// ['Prince  The Revolution', 'When Doves Cry'],
		// ['Evanescence', 'Bring Me To Life'],
		// ['Froukje', 'Ik Wil Dansen'],
		// ['Jim Croce', 'Time In A Bottle'],
		// ['New Order', 'Blue Monday '],
		// ['Simple Minds', 'Alive And Kicking'],
		// ['ABBA', 'Voulez-Vous'],
		// ['Doe Maar', 'Smoorverliefd'],
		// ['Novastar', 'Wrong'],
		// ['White Lies', 'Time To Give'],
		// ['Tame Impala', 'Let It Happen '],
		// ['Acda  De Munnik', 'Ren Lenny Ren'],
		// ['Queen', 'We Are The Champions'],
		// ['Bob Marley  The Wailers', 'No Woman No Cry (Live)'],
		// ['Bob Marley  The Wailers', 'Redemption Song'],
		// ['Kate Bush', 'Cloudbusting'],
		// ['The Doors', 'The End'],
		// ['Neil Diamond', 'I Am... I Said'],
		// ['Doe Maar', 'De Bom'],
		// ['BLØF', 'Dansen Aan Zee'],
		// ['Joe Cocker', 'With A Little Help From My Friends'],
		// ['The Beatles', 'Penny Lane'],
		// ['Anita Meyer', 'Why Tell Me Why'],
		// ['The Police', 'Message In A Bottle'],
		// ['Imagine Dragons', 'Radioactive'],
		// ['The Boxer Rebellion', 'Diamonds'],
		// ['Queen', 'Another One Bites The Dust'],
		// ['Anouk', 'Lost'],
		// ['George Michael', 'A Different Corner'],
		// ['Donna Summer', 'I Feel Love'],
		// ['The Smiths', 'There Is a Light That Never Goes Out'],
		// ['Adele', 'When We Were Young'],
		// ['Het Goede Doel', 'Alles Geprobeerd '],
		// ['Earth, Wind  Fire', 'Fantasy'],
		// ['Eminem', 'Without Me'],
		// ['ChefSpecial', 'In Your Arms'],
		// ['Bee Gees', 'Stayin Alive'],
		// ['Muse', 'Supermassive Black Hole'],
		// ['Kings Of Leon', 'Sex On Fire'],
		// ['Don McLean', 'American Pie '],
		// ['Lex Uiting', 'Nao t Zuuje'],
		// ['Stromae', 'Papaoutai'],
		// ['Van Morrison', 'Brown Eyed Girl'],
		// ['Muse', 'Plug In Baby'],
		// ['Scorpions', 'Still Loving You'],
		// ['Billie Eilish', 'Bad Guy'],
		// ['Stranglers', 'Golden Brown'],
		// ['Spinvis', 'Kom Terug'],
		// ['Iron Maiden', 'The Trooper'],
		// ['Foo Fighters', 'Learn To Fly'],
		// ['Bruce Springsteen', 'Badlands'],
		// ['Golden Earring', 'Going To The Run'],
		// ['Imagine Dragons', 'Demons'],
		// ['Acda  De Munnik', 'Niet Of Nooit Geweest'],
		// ['The War On Drugs', 'Under The Pressure '],
		// ['Orchestral Manoeuvres In The Dark', 'Joan Of Arc (Maid Of Orleans)'],
		// ['Racoon', 'De Echte Vent'],
		// ['Eminem', 'The Real Slim Shady'],
		// ['Kane', 'Rain Down On Me'],
		// ['Golden Earring', 'Long Blond Animal'],
		// ['Michael Jackson', 'Smooth Criminal'],
		// ['De Dijk', 'Ik Kan Het Niet Alleen'],
		// ['Eric Clapton', 'Layla (Unplugged)'],
		// ['George Michael', 'Cowboys And Angels '],
		// ['Bee Gees', 'How Deep Is Your Love'],
		// ['Queen', 'Crazy Little Thing Called Love'],
		// ['Muse', 'Starlight'],
		// ['Boudewijn de Groot', 'De Vondeling Van Ameland'],
		// ['Fleetwood Mac', 'Dont Stop'],
		// ['Iron Maiden', 'Wasted Years'],
		// ['Liquido', 'Narcotic'],
		// ['Editors', 'Smokers Outside The Hospital Doors'],
		// ['Frankie Goes To Hollywood', 'The Power Of Love'],
		// ['Neet Oét Lottum', 'Hald Mich s Vas'],
		// ['Linkin Park', 'Breaking The Habit'],
		// ['Hero', 'Toen Ik Je Zag'],
		// ['America', 'A Horse With No Name'],
		// ['De Staat', 'Witch Doctor'],
		// ['David Bowie', 'Lets Dance'],
		// ['Pink Floyd', 'High Hopes'],
		// ['Neil Young', 'Old Man'],
		// ['Phil Collins', 'Youll Be In My Heart'],
		// ['Marvin Gaye', 'Whats Going On'],
		// ['ABBA', 'Happy New Year'],
		// ['Johnny Cash', 'I Walk The Line'],
		// ['Nightwish', 'Élan '],
		// ['Seal', 'Kiss From A Rose'],
		// ['Joy Division', 'Love Will Tear Us Apart'],
		// ['Creedence Clearwater Revival', 'Wholl Stop The Rain?'],
		// ['Robbie Williams', 'Feel '],
		// ['Boudewijn de Groot', 'Welterusten Mijnheer De President'],
		// ['P!nk', 'What About Us'],
		// ['Rowwen Hèze', 'Limburg (Live)'],
		// ['Johnny Cash', 'Folsom Prison Blues (Live)'],
		// ['Fleetwood Mac', 'Tusk'],
		// ['Talking Heads', 'Psycho Killer'],
		// ['Bruce Springsteen', 'Glory Days'],
		// ['Gorillaz', 'Feel Good Inc.'],
		// ['AC/DC', 'You Shook Me All Night Long'],
		// ['Eva Cassidy', 'Fields Of Gold'],
		// ['The Doors', 'L.A. Woman'],
		// ['Édith Piaf', 'Non, Je Ne Regrette Rien'],
		// ['Het Goede Doel', 'België'],
		// ['John Legend', 'All Of Me'],
		// ['Elton John', 'Goodbye Yellow Brick Road'],
		// ['Imagine Dragons', 'Believer'],
		// ['Radiohead', 'Exit Music (For A Film)'],
		// ['Europe', 'The Final Countdown'],
		// ['Oasis', 'Champagne Supernova '],
		// ['Avicii', 'Levels'],
		// ['Fleetwood Mac', 'Rhiannon (Will You Ever Win)'],
		// ['Green Day', 'Wake Me Up When September Ends'],
		// ['Massive Attack', 'Unfinished Sympathy'],
		// ['Herbert Grönemeyer', 'Halt Mich'],
		// ['London Grammar', 'Strong'],
		// ['Aretha Franklin', 'Respect'],
		// ['Talking Heads', 'Slippery People (Live)'],
		// ['ChefSpecial', 'Amigo'],
		// ['Red Hot Chili Peppers', 'Snow (Hey Oh)'],
		// ['Vangelis', 'Conquest Of Paradise'],
		// ['Nirvana', 'Where Did You Sleep Last Night (unplugged)'],
		// ['David Bowie', 'Life On Mars'],
		// ['The Cure', 'Lullaby'],
		// ['John Denver', 'Leaving On A Jet Plane'],
		// ['2Pac', 'Changes'],
		// ['Amy MacDonald', 'This Is The Life'],
		// ['Mumford  Sons', 'The Cave'],
		// ['Kensington', 'Streets'],
		// ['U2', 'New Years Day'],
		// ['Buena Vista Social Club', 'Chan Chan'],
		// ['Tenacious D', 'Tribute'],
		// ['The War On Drugs', 'Thinking Of A Place '],
		// ['Passenger', 'Let Her Go'],
		// ['Taylor Swift', 'Willow'],
		// ['Guus Meeuwis', 'Geef Mij Je Angst'],
		// ['Andrea Bocelli  Sarah Brightman', 'Time To Say Goodbye'],
		// ['The Cats', 'Lea'],
		// ['Red Hot Chili Peppers', 'Scar Tissue'],
		// ['Iron Maiden', 'Can I Play With Madness'],
		// ['Heart', 'Alone'],
		// ['Golden Earrings', 'Just A Little Bit Of Peace In My Heart'],
		// ['Nothing But Thieves', 'Overcome'],
		// ['ABBA', 'Take A Chance On Me'],
		// ['Adele', 'Easy On Me'],
		// ['INXS', 'Never Tear Us Apart'],
		// ['Elvis Costello', 'She'],
		// ['Avicii', 'Hey Brother'],
		// ['Sting', 'Shape Of My Heart'],
		// ['Alanis Morissette', 'Ironic'],
		// ['Bruce Springsteen', 'Thunder Road'],
		// ['Paul de Leeuw', 'k Heb Je Lief'],
		// ['Sting', 'Russians'],
		// ['Linkin Park  Jay-Z', 'Numb/Encore'],
		// ['The Beatles', 'Strawberry Fields Forever'],
		// ['Santana', 'Samba Pa Ti'],
		// ['The Rolling Stones', 'Wild Horses'],
		// ['Elton John', 'Circle Of Life'],
		// ['Billy Joel', 'Vienna'],
		// ['Whitney Houston', 'I Will Always Love You'],
		// ['Toto', 'Rosanna '],
		// ['Rammstein', 'Mutter'],
		// ['Van Halen', 'Jump'],
		// ['Fleetwood Mac', 'Albatross'],
		// ['Maroon 5', 'Memories'],
		// ['Neil Young', 'Rockin In The Free World'],
		// ['Guns N Roses', 'Patience'],
		// ['Leonard Cohen', 'Suzanne'],
		// ['Chris Rea', 'Driving Home For Christmas'],
		// ['Bruce Springsteen', 'Trapped (Live)'],
		// ['Simple Minds', 'Waterfront'],
		// ['Maan', 'Ze Huilt Maar Ze Lacht'],
		// ['Van Halen', 'Runnin With The Devil'],
		// ['Krezip', 'Sweet Goodbyes'],
		// ['The Black Keys', 'Little Black Submarines'],
		// ['Rob de Nijs', 'Banger Hart'],
		// ['Supertramp', 'Dreamer'],
		// ['Bon Jovi', 'Always '],
		// ['Tame Impala', 'The Less I Know The Better'],
		// ['Eric Clapton', 'Wonderful Tonight'],
		// ['Taylor Swift', 'Shake It Off'],
		// ['10cc', 'Im Not In Love '],
		// ['Billy Joel', 'Leningrad'],
		// ['RagnBone Man', 'Human'],
		// ['Pink Floyd', 'Hey You'],
		// ['Arctic Monkeys', 'I Bet You Look Good On The Dancefloor'],
		// ['Alice In Chains', 'Would'],
		// ['Radiohead', 'No Surprises'],
		// ['Claude', 'Ladada (Mon Dernier Mot)'],
		// ['ABBA', 'I Have A Dream'],
		// ['The Kinks', 'Lola (Live)'],
		// ['Thomas Acda, Paul de Munnik, Maan  Typhoon', 'Als Ik Je Weer Zie'],
		// ['The Cats', 'One Way Wind'],
		// ['R.E.M.', 'Nightswimming'],
		// ['George Michael', 'Freedom! 90'],
		// ['Anouk', 'Birds'],
		// ['Alice Cooper', 'Halo Of Flies'],
		// ['Led Zeppelin', 'Immigrant Song'],
		// ['UB40', 'Red Red Wine'],
		// ['Robbie Williams', 'Let Me Entertain You'],
		// ['U2', 'I Will Follow (Live)'],
		// ['Pink Floyd', 'Us And Them '],
		// ['Gotye ft. Kimbra', 'Somebody That I Used To Know'],
		// ['Bronski Beat', 'Smalltown Boy'],
		// ['Melissa Etheridge', 'Like The Way I Do'],
		// ['Billie Eilish', 'Happier Than Ever'],
		// ['Gerry  The Pacemakers', 'Youll Never Walk Alone'],
		// ['George Michael', 'Faith'],
		// ['Louis Armstrong', 'What A Wonderful World'],
		// ['The Beatles', 'Now And Then'],
		// ['Frank Boeijen Groep', 'De Verzoening'],
		// ['Daniël Lohues', 'Hier Kom Ik Weg'],
		// ['George Michael', 'Father Figure'],
		// ['Men At Work', 'Down Under'],
		// ['Massive Attack', 'Teardrop'],
		// ['Elton John', 'Nikita'],
		// ['Simon  Garfunkel', 'Mrs. Robinson'],
		// ['Prince  The Revolution', 'Sometimes It Snows In April'],
		// ['Dorus', 'Twee Motten'],
		// ['Queen', 'Hammer To Fall '],
		// ['Simply Red', 'Holding Back The Years'],
		// ['Ennio Morricone', 'Once Upon A Time In The West'],
		// ['Aretha Franklin', 'I Say A Little Prayer'],
		// ['Muse', 'Bliss'],
		// ['Lynyrd Skynyrd', 'Sweet Home Alabama'],
		// ['Ed Sheeran', 'I See Fire'],
		// ['Linkin Park', 'One More Light'],
		// ['Michael Jackson', 'Dirty Diana'],
		// ['Don Henley', 'The Boys Of Summer'],
		// ['Status Quo', 'Roll Over Lay Down (Live)'],
		// ['De Poemas', 'Zij Maakt Het Verschil'],
		// ['Al Stewart', 'Year Of The Cat '],
		// ['Eddie Vedder', 'Guaranteed'],
		// ['Status Quo', 'Whatever You Want'],
		// ['Spandau Ballet', 'Through The Barricades'],
		// ['Gerry Rafferty', 'Baker Street '],
		// ['Metallica', 'The Unforgiven II '],
		// ['The Beatles', 'Something'],
		// ['Ozzy Osbourne', 'No More Tears'],
		// ['Aerosmith', 'I Dont Want To Miss A Thing '],
		// ['Tears For Fears  Oleta Adams', 'Woman In Chains '],
		// ['Blue Öyster Cult', 'Dont Fear The Reaper'],
		// ['Foo Fighters', 'My Hero (Live)'],
		// ['Silk Sonic (Bruno Mars  Anderson .Paak)', 'Leave The Door Open'],
		// ['ABBA', 'Knowing Me Knowing You'],
		// ['Stromae', 'Alors On Danse'],
		// ['Guus Meeuwis', 'Dat Komt Door Jou'],
		// ['Peter Schilling', 'Major Tom (Völlig Losgelöst)'],
		// ['10cc', 'Dreadlock Holiday'],
		// ['Acda  De Munnik', 'De Kapitein Deel II'],
		// ['Temptations', 'Papa Was A Rolling Stone '],
		// ['AC/DC', 'Let There Be Rock'],
		// ['Elton John', 'Tiny Dancer'],
		// ['Bastille', 'Pompeii'],
		// ['John Mayer', 'Slow Dancing In A Burning Room'],
		// ['Ed Sheeran', 'Thinking Out Loud'],
		// ['Red Hot Chili Peppers', 'Otherside'],
		// ['The Beatles', 'Come Together'],
		// ['Paul de Leeuw  Simone Kleinsma', 'Zonder Jou'],
		// ['The Beatles', 'The Long And Winding Road'],
		// ['Acda  De Munnik', 'Als Het Vuur Gedoofd Is'],
		// ['Jimi Hendrix', 'Hey Joe'],
		// ['Talk Talk', 'Such A Shame'],
		// ['Joe Jackson', 'Is She Really Going Out With Him? (Live)'],
		// ['Harry Styles', 'Golden'],
		// ['Beyoncé', 'Halo'],
		// ['The Cure', 'Friday Im In Love'],
		// ['Davina Michelle', 'Duurt Te Lang'],
		// ['Crowded House', 'Dont Dream Its Over'],
		// ['The Band', 'The Weight'],
		// ['Crosby, Stills, Nash  Young', 'Our House'],
		// ['Bon Jovi', 'Its My Life'],
		// ['Herbert Grönemeyer', 'Der Weg'],
		// ['ABBA', 'Fernando'],
		// ['Amy Winehouse', 'Rehab'],
		// ['ABBA', 'Super Trouper'],
		// ['Elton John', 'Candle In The Wind 1997'],
		// ['Van Morrison', 'Have I Told You Lately'],
		// ['The Doors', 'Light My Fire '],
		// ['Anouk', 'Michel'],
		// ['One Direction', 'Story Of My Life'],
		// ['Madness', 'One Step Beyond'],
		// ['Genesis', 'Firth Of Fifth'],
		// ['Korn', 'Freak On A Leash'],
		// ['De Dijk', 'Onderuit'],
		// ['P!nk ft. Nate Ruess', 'Just Give Me A Reason'],
		// ['Coldplay', 'Everglow '],
		// ['Boudewijn de Groot', 'Jimmy'],
		// ['The Prodigy', 'Smack My Bitch Up'],
		// ['The Beach Boys', 'Good Vibrations'],
		// ['P!nk', 'Try'],
		// ['Rowwen Hèze', 'Auto Vliegtuug'],
		// ['Guus Meeuwis  Vagant', 'Het Is Een Nacht... (Levensecht)'],
		// ['De Dijk', 'Bloedend Hart'],
		// ['Frank Boeijen Groep', 'Zwart Wit'],
		// ['The Cure', 'Boys Dont Cry'],
		// ['Rolling Stones ft. Lady Gaga  Stevie Wonder', 'Sweet Sounds Of Heaven '],
		// ['Florence + The Machine', 'Dog Days Are Over'],
		// ['Ed Sheeran', 'Shape Of You'],
		// ['Taylor Swift', 'Blank Space'],
		// ['Mariah Carey', 'All I Want For Christmas Is You'],
		// ['Elvis Presley', 'Jailhouse Rock'],
		// ['Johnny Cash', 'A Boy Named Sue (Live)'],
		// ['Dolly Parton', '9 To 5'],
		// ['Skunk Anansie', 'Weak'],
		// ['Sia', 'Chandelier'],
		// ['Duran Duran', 'Ordinary World'],
		// ['Neil Young', 'Like A Hurricane '],
		// ['Green Day', 'Good Riddance (Time Of Your Life)'],
		// ['Sam Fender', 'Seventeen Going Under'],
		// ['Ed Sheeran', 'Castle On The Hill'],
		// ['Fish', 'A Gentlemans Excuse Me'],
		// ['De Dijk', 'Binnen Zonder Kloppen'],
		// ['Dean Lewis', 'How Do I Say Goodbye'],
		// ['Maaike Ouboter', 'Dat Ik Je Mis'],
		// ['Queen', 'I Want It All'],
		// ['Elvis Presley', 'Burning Love'],
		// ['Valensia', 'Gaia'],
		// ['Sade', 'Smooth Operator'],
		// ['Harry Styles', 'Watermelon Sugar'],
		// ['Blur', 'Song 2'],
		// ['Måneskin', 'Zitti E Buoni'],
		// ['Beastie Boys', 'Sabotage'],
		// ['Dire Straits', 'Tunnel Of Love '],
		// ['Keane', 'Sovereign Light Cafe'],
		// ['Bruce Springsteen', 'Jungleland'],
		// ['Mumford  Sons', 'I Will Wait'],
		// ['Marillion', 'Lavender'],
		// ['Green Day', 'American Idiot'],
		// ['David Guetta  Sia', 'Titanium'],
		// ['Prince', '1999'],
		// ['Armin van Buuren ft. Trevor Guthrie', 'This Is What It Feels Like'],
		// ['The Weeknd', 'Save Your Tears'],
		// ['Henk Westbroek', 'Zelfs Je Naam Is Mooi'],
		// ['Eagles', 'New Kid In Town'],
		// ['Supertramp', 'Take The Long Way Home'],
		// ['Simple Minds', 'New Gold Dream (81-82-83-84)'],
		// ['Dusty Springfield', 'Son Of A Preacher Man'],
		// ['Focus', 'Hocus Pocus'],
		// ['Michael Jackson', 'They Dont Care About Us'],
		// ['ABBA', 'One Of Us'],
		// ['Dire Straits', 'On Every Street'],
		// ['Mike Oldfield', 'Tubular Bells (Part 1 Albumversie)'],
		// ['The Rolling Stones', 'Shes A Rainbow'],
		// ['Neil Diamond', 'Beautiful Noise'],
		// ['Bryan Adams', '(Everything I Do) I Do It For You '],
		// ['Ks Choice', 'Not An Addict'],
		// ['Oôs Joôs', 'Bloemkôle'],
		// ['Lewis Capaldi', 'Before You Go'],
		// ['Genesis', 'Follow You Follow Me'],
		// ['Righteous Brothers', 'Unchained Melody'],
		// ['Live', 'Overcome'],
		// ['Moby', 'Porcelain'],
		// ['Billie Eilish', 'Everything I Wanted'],
		// ['Art Garfunkel', 'Bright Eyes'],
		// ['Bankzitters', 'Cupido'],
		// ['Red Hot Chili Peppers', 'Cant Stop'],
		// ['Spandau Ballet', 'Gold'],
		// ['Pixies', 'Where Is My Mind'],
		// ['Cat Stevens', 'Morning Has Broken'],
		// ['Suzan  Freek', 'Blauwe Dag'],
		// ['Guns N Roses', 'Dont Cry'],
		// ['Nits', 'In The Dutch Mountains'],
		// ['Herman van Veen', 'Liefde Van Later'],
		// ['De Poemas', 'Mijn Houten Hart'],
		// ['Nickelback', 'How You Remind Me'],
		// ['Coldplay', 'Christmas Lights'],
		// ['Offspring', 'Self Esteem'],
		// ['Uriah Heep', 'Easy Livin'],
		// ['Guns N Roses', 'Civil War'],
		// ['Herman Brood  His Wild Romance', 'Never Be Clever'],
		// ['My Chemical Romance', 'Welcome To The Black Parade'],
		// ['David Bowie', 'China Girl'],
		// ['Harry Styles', 'Kiwi'],
		// ['Queen', 'A Kind Of Magic'],
		// ['Prince', 'Sign O The Times '],
		// ['Stevie Wonder', 'Superstition'],
		// ['Foo Fighters', 'Walk'],
		// ['Rowwen Hèze', 'De Neus Umhoeg'],
		// ['Bruce Springsteen', 'Jersey Girl (Live)'],
		// ['Genesis', 'Land Of Confusion'],
		// ['Gorillaz', 'Clint Eastwood'],
		// ['The Chainsmokers  Coldplay', 'Something Just Like This'],
		// ['Cat Stevens', 'Father And Son'],
		// ['Madonna', 'Like A Prayer'],
		// ['Derek  The Dominos', 'Layla '],
		// ['Armin van Buuren ft. Kensington', 'Heading Up High'],
		// ['Mark Knopfler', 'What It Is'],
		// ['Typhoon', 'Zandloper'],
		// ['The Rolling Stones', 'Start Me Up'],
		// ['Nick Cave  Kylie Minogue', 'Where The Wild Roses Grow'],
		// ['Kensington', 'War'],
		// ['Rick Astley', 'Never Gonna Give You Up'],
		// ['Rod Stewart', 'Sailing'],
		// ['Elton John  Dua Lipa', 'Cold Heart (Pnau Remix)'],
		// ['Eagles', 'Lyin Eyes'],
		// ['Santana', 'Shes Not There '],
		// ['John Mayer', 'Gravity'],
		// ['The Prodigy', 'Firestarter'],
		// ['Rob de Nijs', 'Malle Babbe'],
		// ['Arctic Monkeys', 'When The Sun Goes Down'],
		// ['Adele', 'Million Years Ago'],
		// ['Joe Cocker', 'You Are So Beautiful'],
		// ['Michael Jackson', 'Heal The World '],
		// ['Mark Ronson ft. Bruno Mars', 'Uptown Funk'],
		// ['Franz Ferdinand', 'Take Me Out'],
		// ['4 Non Blondes', 'Whats Up'],
		// ['Cream', 'White Room '],
		// ['The Black Eyed Peas', 'I Gotta Feeling'],
		// ['The Beatles', 'Norwegian Wood'],
		// ['Paolo Nutini', 'Through The Echoes'],
		// ['Gilbert OSullivan', 'Nothing Rhymed'],
		// ['Tori Amos', 'Winter'],
		// ['Mike Oldfield  Maggie Reilly', 'Moonlight Shadow'],
		// ['Killing Joke', 'Love Like Blood'],
		// ['Depeche Mode', 'Personal Jesus'],
		// ['The Script', 'The Man Who Cant Be Moved'],
		// ['The Teskey Brothers', 'Pain And Misery'],
		// ['Andrea Bocelli', 'Con Te Partiro'],
		// ['Fools Garden', 'Lemon Tree'],
		// ['The War On Drugs', 'Red Eyes'],
		// ['Eros Ramazzotti', 'Musica È '],
		// ['Taylor Swift', 'You Need To Calm Down'],
		// ['Ten Sharp', 'You'],
		// ['Nirvana', 'Heart-Shaped Box'],
		// ['Charly Lownoise  Mental Theo', 'Wonderfull Days'],
		// ['Imagine Dragons', 'Thunder'],
		// ['Doe Maar', 'Is Dit Alles'],
		// ['Niall Horan', 'This Town'],
		// ['Dire Straits', 'Your Latest Trick'],
		// ['The Blue Nile', 'Tinseltown In The Rain'],
		// ['Joni Mitchell', 'Both Sides Now'],
		// ['Queens Of The Stone Age', 'Go With The Flow'],
		// ['Fleetwood Mac', 'Need Your Love So Bad'],
		// ['Talking Heads', 'Once In A Lifetime'],
		// ['Aretha Franklin', '(You Make Me Feel Like A) Natural Woman'],
		// ['ChefSpecial', 'Afraid Of The Dark'],
		// ['Yes', 'Owner Of A Lonely Heart'],
		// ['De Kast', 'In Nije Dei'],
		// ['Ram Jam', 'Black Betty '],
		// ['Bryan Adams', 'Heaven'],
		// ['The Pogues', 'Dirty Old Town'],
		// ['Within Temptation', 'Stand My Ground'],
		// ['Venice', 'The Family Tree'],
		// ['Phil Collins  Philip Bailey', 'Easy Lover'],
		// ['The Opposites', 'Slapeloze Nachten'],
		// ['David Bowie', 'Wild Is The Wind'],
		// ['Dr. Dre ft. Snoop Dogg', 'The Next Episode'],
		// ['Whitney Houston', 'I Wanna Dance With Somebody (Who Loves Me)'],
		// ['Aretha Franklin', 'Think (Blues Brothers Version)'],
		// ['The Killers', 'Human'],
		// ['Whitesnake', 'Here I Go Again'],
		// ['André Hazes Jr.', 'Leef'],
		// ['Muse', 'Unintended'],
		// ['Smashing Pumpkins', 'Disarm'],
		// ['Donna Summer', 'State Of Independence'],
		// ['Harry Styles', 'Late Night Talking'],
		// ['The Gathering', 'Strange Machines '],
		// ['Normaal', 'De Boer Dat Is De Keerl'],
		// ['Racoon', 'Tijd Verliezen'],
		// ['Nena  Kim Wilde', 'Anyplace, Anywhere, Anytime'],
		// ['Within Temptation', 'Faster'],
		// ['Survivor', 'Eye Of The Tiger'],
		// ['Post Malone', 'Circles'],
		// ['Iggy Pop', 'The Passenger'],
		// ['Daniël Lohues', 'Prachtig Mooie Dag'],
		// ['Bruce Springsteen', 'The Rising'],
		// ['Soft Cell', 'Tainted Love'],
		// ['De Jeugd Van Tegenwoordig', 'Watskeburt?!'],
		// ['Michael Jackson', 'Ben'],
		// ['John Mayer', 'Daughters'],
		// ['Chi Coltrane', 'Go Like Elijah'],
		// ['Shocking Blue', 'Venus'],
		// ['Gloria Gaynor', 'I Will Survive'],
		// ['Tavares', 'Heaven Must Be Missing An Angel'],
		// ['Pharrell Williams', 'Happy'],
		// ['Eminem  Rihanna', 'Love The Way You Lie'],
		// ['Cockney Rebel', 'Sebastian '],
		// ['Lisa Lois', 'Hallelujah'],
		// ['Depeche Mode', 'Just Cant Get Enough (Live)'],
		// ['BLØF', 'Blauwe Ruis'],
		// ['Blondie', 'Denis'],
		// ['Enya', 'Only Time'],
		// ['Red Hot Chili Peppers', 'Dark Necessities'],
		// ['Herman Brood', 'My Way'],
		// ['Live', 'I Alone'],
		// ['Supertramp', 'Give A Little Bit'],
		// ['John Mayer', 'In The Blood'],
		// ['Simon  Garfunkel', 'El Condor Pasa (If I Could)'],
		// ['Racoon', 'Dont Give Up The Fight'],
		// ['Fischer-Z', 'So Long'],
		// ['Moby', 'Why Does My Heart Feel So Bad'],
		// ['Eros Ramazzotti  Tina Turner', 'Cose Della Vita'],
		// ['The Police', 'Every Little Thing She Does Is Magic'],
		// ['Miley Cyrus', 'Flowers'],
		// ['Santana', 'Black Magic Woman'],
		// ['Supertramp', 'Breakfast In America'],
		// ['Bon Jovi', 'You Give Love A Bad Name'],
		// ['Leonard Cohen', 'You Want It Darker'],
		// ['De Dijk', 'Als Het Golft'],
		// ['Nazareth', 'Love Hurts'],
		// ['Froukje', 'Niets Tussen'],
		// ['Harry Styles', 'Treat People With Kindness'],
		// ['Bob Dylan', 'Blowin In The Wind'],
		// ['Crosby, Stills, Nash  Young', 'Teach Your Children'],
		// ['Leonard Cohen', 'Dance Me To The End Of Love'],
		// ['Bökkers', 'Iederene Hef Een Reden'],
		// ['Barry White', 'Youre The First, The Last, My Everything'],
		// ['Meat Loaf', 'You Took The Words Right Out Of My Mouth (Hot Summer Night) '],
		// 	['Eddie Vedder', 'Hard Sun'],
		// 	['Paul Simon', 'You Can Call Me Al'],
		// 	['Bob Marley  The Wailers', 'Could You Be Loved'],
		// 	['Joe Jackson', 'Be My Number Two'],
		// 	['John Denver  Placido Domingo', 'Perhaps Love'],
		// 	['Crosby, Stills, Nash  Young', 'Almost Cut My Hair'],
		// 	['The Alan Parsons Project', 'The Turn Of A Friendly Card'],
		// 	['Mark Knopfler  James Taylor', 'Sailing To Philadelphia '],
		// 	['ABBA', 'S.O.S.'],
		// 	['Elvis Presley', 'I Just Cant Help Believin'],
		// 	['Carly Simon', 'Youre So Vain'],
		// 	['The Black Keys', 'Lonely Boy'],
		// 	['Ed Sheeran', 'The A Team'],
		// 	['David Bowie', 'Sound And Vision'],
		// 	['David Bowie  Mick Jagger', 'Dancing In The Street'],
		// 	['The Beatles', 'Get Back'],
		// 	['Racoon', 'Geef Je Hart Niet Zomaar Weg'],
		// 	['DI-RECT', 'Times Are Changing'],
		// 	['Tears For Fears', 'Shout'],
		// 	['Damien Rice', '9 Crimes'],
		// 	['Frank Sinatra', 'Thats Life'],
		// 	['Stone Temple Pilots', 'Plush'],
		// 	['Joe Jackson', 'Real Men'],
		// 	['Leonard Cohen', 'So Long Marianne'],
		// 	['Simple Minds', 'Someone Somewhere In Summertime'],
		// 	['Red Hot Chili Peppers', 'Road Trippin'],
		// 	['Marco Borsato', 'Margherita'],
		// 	['Wham!', 'Wake Me Up Before You Go-Go'],
		// 	['Genesis', 'Jesus He Knows Me'],
		// 	['Michel Sardou', 'Les Lacs Du Connemara'],
		// 	['Toontje Lager', 'Stiekem Gedanst'],
		// 	['David Bowie', 'Rebel Rebel'],
		// 	['Crowded House', 'Four Seasons In One Day'],
		// 	['Bee Gees', 'More Than A Woman'],
		// 	['Chris de Burgh', 'The Lady In Red'],
		// 	['Paul Simon', 'Diamonds On The Soles Of Her Shoes '],
		// 	['Coldplay', 'Adventure Of A Lifetime'],
		// 	['André Hazes  Paul de Leeuw', 'Droomland'],
		// 	['Black Pumas', 'Colors'],
		// 	['De Dijk', 'Kan Ik Iets Voor Je Doen?'],
		// 	['UB40', 'Kingston Town'],
		// 	['Céline Dion', 'Its All Coming Back To Me'],
		// 	['Earth, Wind  Fire  The Emotions', 'Boogie Wonderland'],
		// 	['Kensington', 'Riddles'],
		// 	['Rowwen Hèze', 'Vlinder'],
		// 	['Supertramp', 'Crime Of The Century'],
		// 	['Queen', 'Breakthru'],
		// 	['Spice Girls', 'Wannabe'],
		// 	['Donna Summer', 'MacArthur Park'],
		// 	['Rammstein', 'Radio'],
		// 	['George Michael', 'Praying For Time'],
		// 	['Coldplay', 'Magic'],
		// 	['Dexys Midnight Runners', 'Come On Eileen '],
		// 	['The Rolling Stones', 'Miss You '],
		// 	['Golden Earring', 'She Flies On Strange Wings '],
		// 	['Talk Talk', 'Its My Life'],
		// 	['The Cats', 'Marian'],
		// 	['Tina Turner', 'Whats Love Got To Do With It'],
		// 	['Ike  Tina Turner', 'Nutbush City Limits'],
		// 	['Doe Maar', 'Nederwiet '],
		// 	['Elvis Costello', 'I Want You'],
		// 	['The Beatles', 'The Fool On The Hill'],
		// 	['Queen', 'Youre My Best Friend'],
		// 	['Twenty One Pilots', 'Stressed Out'],
		// 	['Train', 'Drops Of Jupiter (Tell Me)'],
		// 	['Limp Bizkit', 'Behind Blue Eyes'],
		// 	['George Michael', 'Killer/Papa Was A Rollin Stone'],
		// 	['Beth Hart  Joe Bonamassa', 'Ill Take Care Of You '],
		// 	['Enya', 'Orinoco Flow (Sail Away)'],
		// 	['Adele', 'Hometown Glory '],
		// 	['Taylor Swift', 'Cowboy Like Me'],
		// 	['Robbie Williams', 'Mr. Bojangles'],
		// 	['U2', 'All I Want Is You '],
		// 	['Etta James', 'At Last'],
		// 	['Status Quo', 'Down Down'],
		// 	['BLØF', 'Hou Vol Hou Vast'],
		// 	['Madness', 'Our House'],
		// 	['Jimi Hendrix', 'Voodoo Child (Slight Return)'],
		// 	['Ed Sheeran', 'Photograph'],
		// 	['Barbra Streisand', 'Woman In Love'],
		// 	['Roxette', 'Listen To Your Heart '],
		// 	['2Pac ft. Dr. Dre', 'California Love'],
		// 	['John Farnham', 'Youre The Voice'],
		// 	['Arctic Monkeys', 'Fluorescent Adolescent'],
		// 	['Paul McCartney  Wings', 'Band On The Run'],
		// 	['Racoon', 'No Mercy'],
		// 	['Snelle  Maan', 'Blijven Slapen'],
		// 	['Coldplay', 'Hymn For The Weekend'],
		// 	['The Rolling Stones', 'Brown Sugar'],
		// 	['Harry Styles', 'Adore You'],
		// 	['Backstreet Boys', 'I Want It That Way'],
		// 	['Barbra Streisand  Barry Gibb', 'Guilty'],
		// 	['The Cure', 'Close To Me'],
		// 	['Guus Meeuwis', 'Tranen Gelachen'],
		// 	['Smashing Pumpkins', '1979'],
		// 	['Editors', 'Munich'],
		// 	['Lou Reed', 'Walk On The Wild Side'],
		// 	['Iggy Pop', 'Lust For Life'],
		// 	['S10', 'De Diepte'],
		// 	['Gigi DAgostino', 'LAmour Toujours'],
		// 	['Linkin Park', 'What Ive Done'],
		// 	['Bee Gees', 'Tragedy'],
		// 	['Queen', 'Fat Bottomed Girls '],
		// 	['Muse', 'Time Is Running Out'],
		// 	['Ilse DeLange', 'I Still Cry'],
		// 	['David Bowie', 'Absolute Beginners'],
		// 	['Kensington', 'Do I Ever'],
		// 	['Zucchero', 'Il Volo'],
		// 	['The Doors', 'People Are Strange'],
		// 	['Frank Sinatra', 'Fly Me To The Moon'],
		// 	['Marco Borsato', 'Rood'],
		// 	['Christina Aguilera', 'Hurt'],
		// 	['BLØF', 'Mooie Dag'],
		// 	['R.E.M.', 'Man On The Moon'],
		// 	['Paul Weller', 'You Do Something To Me'],
		// 	['Bruce Springsteen', 'Waiting On A Sunny Day'],
		// 	['Anouk', 'Girl'],
		// 	['BAP', 'Kristallnach'],
		// 	['Portishead', 'Glory Box'],
		// 	['Neil Young', 'Harvest Moon'],
		// 	['First Aid Kit', 'My Silver Lining'],
		// 	['Kaleo', 'Way Down We Go'],
		// 	['Earth  Fire', 'Storm And Thunder'],
		// 	['David Bowie', 'Ashes To Ashes'],
		// 	['Michael Jackson', 'Black Or White'],
		// 	['Adele', 'Chasing Pavements'],
		// 	['The Police', 'So Lonely'],
		// 	['Bob Dylan', 'Like A Rolling Stone'],
		// 	['Heart', 'Barracuda'],
		// 	['Dolly Parton', 'I Will Always Love You'],
		// 	['Red Hot Chili Peppers', 'Give It Away'],
		// 	['Alanis Morissette', 'You Oughta Know'],
		// 	['De Dijk', 'Nergens Goed Voor'],
		// 	['Meat Loaf', 'Two Out Of Three Aint Bad '],
		// 	['No Doubt', 'Dont Speak'],
		// 	['Pearl Jam', 'Better Man'],
		// 	['Jimi Hendrix', 'Little Wing'],
		// 	['André Hazes', 'n Beetje Verliefd'],
		// 	['Red Hot Chili Peppers', 'Dani California'],
		// 	['Robert Miles', 'Children'],
		// 	['The Rolling Stones', 'Waiting On A Friend'],
		// 	['Marianne Rosenberg', 'Ich Bin Wie Du'],
		// 	['Macklemore  Ryan Lewis ft. Ray Dalton', 'Cant Hold Us'],
		// 	['Kanye West  Chris Martin', 'Homecoming'],
		// 	['Prince  The Revolution', 'Raspberry Beret'],
		// 	['Carole King', 'Youve Got A Friend'],
		// 	['Cranberries', 'Ode To My Family'],
		// 	['The Smiths', 'Bigmouth Strikes Again'],
		// 	['ZZ Top', 'Gimme All Your Lovin'],
		// 	['Bee Gees', 'Words'],
		// 	['Nina Simone', 'Aint Got No, I Got Life (Original)'],
		// 	['Radiohead', 'Fake Plastic Trees'],
		// 	['The Beatles', 'Sgt. Peppers Lonely Hearts Club Band'],
		// 	['Creedence Clearwater Revival', 'I Heard It Through The Grapevine'],
		// 	['Rush', 'Spirit Of Radio '],
		// 	['Loreen', 'Euphoria'],
		// 	['Olivia Rodrigo', 'Drivers License'],
		// 	['Xavier Rudd', 'Follow The Sun'],
		// 	['The Black Eyed Peas', 'Where Is The Love'],
		// 	['Elbow', 'Lippy Kids'],
		// 	['Queen', 'Its A Beautiful Day'],
		// 	['Wham!', 'Club Tropicana'],
		// 	['Cyndi Lauper', 'True Colors'],
		// 	['Tracy Chapman', 'Baby Can I Hold You'],
		// 	['Eminem', 'Sing For The Moment'],
		// 	['Ben E. King', 'Stand By Me'],
		// 	['Gladys Knight  The Pips', 'Midnight Train To Georgia'],
		// 	['Triggerfinger', 'I Follow Rivers'],
		// 	['Arctic Monkeys', 'Whyd You Only Call Me When Youre High?'],
		// 	['Flemming', 'Automatisch'],
		// 	['Racoon', 'Liverpool Rain'],
		// 	['Pink Floyd', 'One Of These Days'],
		// 	['Lee Towers', 'Youll Never Walk Alone'],
		// 	['Little River Band', 'Its A Long Way There '],
		// 	['Supertramp', 'Goodbye Stranger '],
		// 	['Coldplay', 'Trouble'],
		// 	['Chicago', 'If You Leave Me Now'],
		// 	['Coldplay', 'Higher Power'],
		// 	['Keane', 'Bedshaped'],
		// 	['Elton John  Kiki Dee', 'Dont Go Breaking My Heart'],
		// 	['Froukje', 'Een Teken'],
		// 	['ABBA', 'Angel Eyes'],
		// 	['Doe Maar', 'Pa'],
		// 	['Imagine Dragons', 'Natural'],
		// 	['One Direction', 'Best Song Ever'],
		// 	['DJ Paul Elstak', 'Luv U More'],
		// 	['Snowy White', 'Bird Of Paradise'],
		// 	['Manic Street Preachers', 'If You Tolerate This Your Children Will Be Next'],
		// 	['Herman van Veen', 'Suzanne'],
		// 	['Diggy Dex', 'De Zon Op'],
		// 	['Keane', 'Everybodys Changing'],
		// 	['George Michael  Aretha Franklin', 'I Knew You Were Waiting (For Me)'],
		// 	['Kanye West  Jay-Z', '..In Paris'],
		// 	['Dire Straits', 'Why Worry '],
		// 	['Racoon', 'Hee Joh Jip'],
		// 	['ZZ Top', 'Sharp Dressed Man'],
		// 	['Creedence Clearwater Revival', 'Suzie Q (Part 1)'],
		// 	['Clannad  Bono', 'In A Lifetime'],
		// 	['Robert Long', 'Flink Zijn'],
		// 	['Neil Diamond', 'September Morn'],
		// 	['Michael Kiwanuka', 'Love And Hate '],
		// 	['John Hiatt', 'Have A Little Faith In Me'],
		// 	['Lucifer', 'House For Sale'],
		// 	['Alice Cooper', 'How You Gonna See Me Now'],
		// 	['Imagine Dragons', 'Whatever It Takes'],
		// 	['Nick  Simon', 'Pak Maar Mijn Hand'],
		// 	['Charles Aznavour', 'Yesterday When I Was Young'],
		// 	['Les Poppys', 'Non Non Rien na Changé'],
		// 	['Queen', '39'],
		// 	['Tiësto', 'Traffic'],
		// 	['ABBA', 'Money Money Money'],
		// 	['Scorpions', 'Send Me An Angel'],
		// 	['Rufus Wainwright', 'Going To A Town'],
		// 	['Marco Borsato, Armin van Buuren, Davina Michelle', 'Hoe Het Danst'],
		// 	['Eagles', 'Tequila Sunrise'],
		// 	['Kansas', 'Carry On Wayward Son '],
		// 	['Clouseau', 'Daar Gaat Ze'],
		// 	['Harry Styles', 'Music For A Sushi Restaurant'],
		// 	['Coldplay x BTS', 'My Universe'],
		// 	['Roxy Music', 'Avalon'],
		// 	['Creedence Clearwater Revival', 'Proud Mary'],
		// 	['Midnight Oil', 'Beds Are Burning'],
		// 	['Taylor Swift', 'I Knew You Were Trouble'],
		// 	['Rammstein', 'Amerika'],
		// 	['The Moody Blues', 'Question'],
		// 	['REO Speedwagon', 'Keep On Loving You'],
		// 	['Alanis Morissette', 'Uninvited'],
		// 	['The Clash', 'London Calling'],
		// 	['Prince  The Revolution', 'I Would Die 4 U'],
		// 	['The Bangles', 'Eternal Flame'],
		// 	['Amy Winehouse', 'Tears Dry On Their Own'],
		// 	['Simon  Garfunkel', 'Homeward Bound'],
		// 	['Madonna', 'Frozen'],
		// 	['Simon  Garfunkel', 'Scarborough Fair'],
		// 	['Boudewijn de Groot', 'Het Land Van Maas En Waal'],
		// 	['Veldhuis  Kemper', 'Ik Wou Dat Ik Jou Was'],
		// 	['Lady Gaga', 'Born This Way'],
		// 	['Carpenters', 'Top Of The World'],
		// 	['Talk Talk', 'Lifes What You Make It'],
		// 	['The Beatles', 'Help!'],
		// 	['U2', 'Running To Stand Still'],
		// 	['Bee Gees', 'Massachusetts'],
		// 	['Skunk Anansie', 'Hedonism'],
		// 	['Madness', 'Night Boat To Cairo'],
		// 	['The Rolling Stones', 'Fool To Cry'],
		// 	['Herman van Veen', 'Hilversum 3'],
		// 	['The Common Linnets', 'Calm After The Storm'],
		// 	['Khruangbin  Leon Bridges', 'Texas Sun'],
		// 	['Ed Sheeran', 'Bad Habits'],
		// 	['Toto', 'Mushanga'],
		// 	['Yann Tiersen', 'Comptine Dun Autre Éte, Lapres Midi (Amelie)'],
		// 	['Nirvana', 'About A Girl (Unplugged)'],
		// 	['Madness', 'Baggy Trousers'],
		// 	['Gé Reinders', 'Blaosmuziek'],
		// 	['R.E.M.', 'Find The River'],
		// 	['Ilse DeLange', 'Miracle'],
		// 	['Iron Butterfly', 'In-A-Gadda-Da-Vida '],
		// 	['The Rembrandts', 'Ill Be There For You'],
		// 	['The War On Drugs', 'Pain'],
		// 	['Foo Fighters', 'Times Like These'],
		// 	['Split Enz', 'Message To My Girl'],
		// 	['Ludovico Einaudi', 'Una Mattina'],
		// 	['The Who', 'Pinball Wizard'],
		// 	['Rowwen Hèze', 'Bestel Mar'],
		// 	['Creedence Clearwater Revival', 'Long As I Can See The Light'],
		// 	['Green Day', '21 Guns'],
		// 	['Anouk', 'One Word'],
		// 	['Danny Vera', 'Pressure Makes Diamonds (2020)'],
		// 	['Talking Heads', 'Road To Nowhere'],
		// 	['Muse', 'Undisclosed Desires'],
		// 	['Air', 'All I Need'],
		// 	['Manic Street Preachers', 'Motorcycle Emptiness'],
		// 	['Paul Kalkbrenner', 'Sky And Sand'],
		// 	['Toto', 'Pamela '],
		// 	['The Teskey Brothers', 'Hold Me'],
		// 	['The Cats', 'Scarlet Ribbons'],
		// 	['Temple Of The Dog', 'Hunger Strike'],
		// 	['Nina Simone', 'Feeling Good'],
		// 	['Blues Brothers', 'Everybody Needs Somebody To Love'],
		// 	['Phil Collins', 'Cant Stop Loving You'],
		// 	['George Michael  Mary J. Blige', 'As'],
		// 	['Pink Floyd', 'Breathe (In The Air)'],
		// 	['Pat Benatar', 'Love Is A Battlefield'],
		// 	['Matthias Reim', 'Verdammt Ich Lieb Dich'],
		// 	['Iggy Pop  Kate Pierson', 'Candy'],
		// 	['Kim Wilde', 'Cambodia'],
		// 	['Tina Turner', 'We Dont Need Another Hero'],
		// 	['Fleetwood Mac', 'Oh Well '],
		// 	['Rob de Nijs', 'Alles Wat Ademt'],
		// 	['Lana Del Rey', 'Doin Time'],
		// 	['Golden Earring', 'Back Home'],
		// 	['John Mayer', 'Free Fallin (Live)'],
		// 	['Bryan Adams', 'Run To You'],
		// 	['Doobie Brothers', 'Listen To The Music'],
		// 	['BLØF', 'Wat Zou Je Doen?'],
		// 	['Daft Punk ft. Pharrell Williams', 'Get Lucky'],
		// 	['Bruno Mars', 'When I Was Your Man'],
		// 	['Curtis Mayfield', 'Move On Up'],
		// 	['John Denver', 'Calypso'],
		// 	['Duran Duran', 'The Reflex'],
		// ['The Beatles', 'Michelle'],
		// ['U2  BB King', 'When Love Comes To Town'],
		// ['Jethro Tull', 'Locomotive Breath'],
		// ['Bee Gees', 'Night Fever'],
		// ['Lenny Kravitz', 'Let Love Rule'],
		// ['Lady Gaga', 'Bad Romance'],
		// ['Roxette', 'It Must Have Been Love'],
		// ['The Beatles', 'In My Life'],
		// ['Jimi Hendrix', 'The Wind Cries Mary'],
		// ['Arcade Fire', 'Everything Now'],
		// ['Manu Chao', 'Me Gustas Tu'],
		// ['Amy Winehouse', 'You Know Im No Good'],
		// ['Metallica', 'The Unforgiven III'],
		// ['Paul Simon', '50 Ways To Leave Your Lover'],
		// ['Green Day', 'Holiday'],
		// ['Bon Jovi', 'Wanted (Dead Or Alive)'],
		// ['Stromae', 'Tous Les Mêmes'],
		// ['Muse', 'Madness'],
		// ['Kenny Rogers', 'The Gambler'],
		// ['Taylor Swift', 'We Are Never Ever Getting Back Together'],
		// ['John Mayer', 'Last Train Home'],
		// ['Placebo', 'Pure Morning'],
		// ['Claw Boys Claw', 'Rosie'],
		// ['Danny Vera', 'Hold On To Let Go'],
		// ['P!nk', 'Raise Your Glass'],
		// ['Trammps', 'Disco Inferno'],
		// ['Krezip', 'Lost Without You'],
		// ['Steppenwolf', 'Born To Be Wild'],
		// ['Counting Crows', 'Mr. Jones'],
		// ['Cuby  the Blizzards', 'Somebody Will Know Someday'],
		// ['Adele', 'Turning Tables'],
		// ['The Killers', 'Somebody Told Me'],
		// ['Sniff n The Tears', 'Drivers Seat'],
		// ['David Bowie', 'Lazarus'],
		// ['Adele', 'All I Ask'],
		// ['Ed Sheeran', 'Supermarket Flowers'],
		// ['Prince', 'Lets Go Crazy'],
		// ['Led Zeppelin', 'Since Ive Been Loving You'],
		// ['Elvis Presley', 'Love Me Tender'],
		// ['Marco Borsato', 'Afscheid Nemen Bestaat Niet'],
		// ['Foo Fighters', 'Best Of You'],
		// ['Bill Withers', 'Lovely Day'],
		// ['Flemming', 'Amsterdam'],
		// ['White Lies', 'Farewell To The Fairground'],
		// ['The Rolling Stones', 'Honky Tonk Women'],
		// ['Heart', 'Crazy On You'],
		// ['George Baker Selection', 'Little Green Bag'],
		// ['Eminem', 'Like Toy Soldiers'],
		// ['Jeff Wayne  Justin Hayward', 'The Eve Of The War '],
		// ['Chuck Berry', 'Johnny B. Goode'],
		// ['Muse', 'Resistance '],
		// ['Justin Timberlake', 'Cant Stop The Feeling!'],
		// ['The Doors', 'Roadhouse Blues'],
		// ['Blink-182', 'All The Small Things'],
		// ['2Pac', 'Dear Mama'],
		// ['Brian May', 'Too Much Love Will Kill You'],
		// ['Suzan  Freek', 'Kwijt'],
		// ['Lynyrd Skynyrd', 'Simple Man'],
		// ['The Rolling Stones', 'Jumpin Jack Flash'],
		// ['Tom Petty', 'Free Fallin'],
		// ['Mr. Mister', 'Broken Wings'],
		// ['Phil Collins', 'I Wish It Would Rain Down'],
		// ['Beth Hart', 'L.A. Song '],
		// ['Dire Straits', 'So Far Away '],
		// ['David Bowie', 'Golden Years'],
		// ['Kodaline', 'All I Want'],
		// ['Billy Joel', 'Scenes From An Italian Restaurant'],
		// ['Status Quo', 'Rockin All Over The World'],
		// ['Barbra Streisand', 'Memory'],
		// ['Nena', 'Nur Geträumt'],
		// ['Queen', 'Bicycle Race'],
		// ['Level 42', 'Lessons In Love'],
		// ['Bush', 'Glycerine'],
		// ['The Rolling Stones', 'Ruby Tuesday'],
		// ['Queens Of The Stone Age', 'Make It Wit Chu'],
		// ['Dire Straits', 'Lady Writer'],
		// ['Elvis Presley', '(Youre) The Devil In Disguise'],
		// ['Kings Of Leon', 'Use Somebody'],
		// ['The Beatles', 'All You Need Is Love'],
		// ['Emerson, Lake  Palmer', 'Peter Gunn Theme'],
		// ['Duran Duran', 'Save A Prayer'],
		// ['Snow Patrol', 'Just Say Yes'],
		// ['Normaal', 'Ik Bun Moar Een Eenvoudige Boerenlul'],
		// ['The Script ft. Will.I.Am', 'Hall Of Fame'],
		// ['Marco Borsato', 'De Bestemming'],
		// ['BLØF', 'Alles Is Liefde'],
		// ['Madonna', 'Live To Tell'],
		// ['Joe Cocker', 'Unchain My Heart'],
		// ['Faithless', 'We Come 1'],
		// ['Lauren Daigle', 'You Say'],
		// ['Thin Lizzy', 'Whisky In The Jar'],
		// ['Melanie', 'Beautiful People'],
		// ['David Bowie', 'Changes'],
		// ['Janis Joplin', 'Cry Baby'],
		// ['Dave Brubeck Quartet', 'Take Five'],
		// ['Kate Bush', 'Babooshka'],
		// ['Billie Eilish', 'When The Partys Over'],
		// ['Natasha Bedingfield', 'Unwritten'],
		// ['Alannah Myles', 'Black Velvet '],
		// ['Herman van Veen', 'Anne'],
		// ['Guus Meeuwis', 'De Weg'],
		// ['Queen', 'Thank God Its Christmas'],
		// ['The Weeknd ft. Daft Punk', 'Starboy'],
		// ['Cock Robin', 'The Promise You Made'],
		// ['Pearl Jam', 'Daughter'],
		// ['Pommelien Thijs  Jaap Reesema', 'Nu Wij Niet Meer Praten'],
		// ['Phil Collins', 'You Cant Hurry Love'],
		// ['Nirvana', 'In Bloom'],
		// ['Peter Gabriel', 'Sledgehammer'],
		// ['Tom Waits', 'Tom Trauberts Blues (Waltzing Mathilda)'],
		// ['P!nk ft. Willow Sage Heart', 'Cover Me In Sunshine'],
		// ['Daft Punk', 'One More Time'],
		// ['The War On Drugs', 'I Dont Live Here Anymore'],
		// ['Prince  The Revolution', 'Kiss'],
		// ['Darude', 'Sandstorm'],
		// ['Bob Dylan', 'The Times They Are A-Changin'],
		// ['David Bowie  Pat Metheny Group', 'This Is Not America'],
		// ['Communards  Sarah Jane Morris', 'Dont Leave Me This Way'],
		// ['Band Aid', 'Do They Know Its Christmas'],
		// ['The Dubliners', 'The Wild Rover (Live)'],
		// ['Rondé', 'Hard To Say Goodbye'],
		// ['Lionel Richie', 'Hello'],
		// ['Fleetwood Mac', 'Seven Wonders'],
		// ['Spinvis', 'Bagagedrager'],
		// ['Clannad', 'Theme From Harrys Game'],
		// ['The Human League', 'Dont You Want Me'],
		// ['Alice Cooper', 'Schools Out'],
		// ['Laura Pausini', 'La Solitudine'],
		// ['Queen', 'Good Old-Fashioned Lover Boy'],
		// ['Eminem', 'My Name Is'],
		// ['Leonard Cohen', 'Take This Waltz'],
		// ['R.E.M.', 'Drive'],
		// ['Marc Cohn', 'Walking In Memphis'],
		// ['Anouk', 'For Bitter Or Worse'],
		// ['Simply Red', 'If You Dont Know Me By Now'],
		// ['Eminem', 'Cleanin Out My Closet'],
		// ['Queen', 'Tie Your Mother Down'],
		// ['Céline Dion', 'My Heart Will Go On'],
		// ['Rob de Nijs', 'Niet Voor Het Laatst'],
		// ['Marco Borsato', 'De Waarheid'],
		// ['Billy Joel', 'We Didnt Start The Fire'],
		// ['Ed Sheeran', 'Shivers'],
		// ['Lady Gaga', 'Poker Face'],
		// ['Pet Shop Boys', 'Its A Sin'],
		// ['Meat Loaf', 'Heaven Can Wait'],
		// ['Het Goede Doel', 'Vriendschap'],
		// ['The Script', 'If You Could See Me Now'],
		// ['Keane', 'Bend And Break'],
		// ['The Beatles', 'Lucy In The Sky With Diamonds'],
		// ['Faith No More', 'Epic'],
		// ['Roberta Flack', 'The First Time Ever I Saw Your Face'],
		// ['Queen', 'Friends Will Be Friends'],
		// ['Patrick Bruel', 'Casser La Voix (Live)'],
		// ['Coldplay', 'Speed Of Sound'],
		// ['Mecano', 'Hijo De La Luna'],
		// ['Live', 'The Dolphins Cry'],
		// ['Peter Gabriel', 'Biko'],
		// ['Cuby  the Blizzards', 'Appleknockers Flophouse'],
		// ['Fugees', 'Killing Me Softly'],
		// ['Kendrick Lamar', 'King Kunta'],
		// ['Suzan  Freek', 'Dromen In Kleur'],
		// ['André Hazes', 'Ik Leef Mijn Eigen Leven'],
		// ['Drs. P', 'Dodenrit'],
		// ['The Police', 'Walking On The Moon'],
		// ['Joe Cocker', 'NOubliez Jamais'],
		// ['Swedish House Mafia ft. The Weeknd', 'Moth To A Flame'],
		// ['Tears For Fears', 'Sowing The Seeds Of Love'],
		// ['Johnny Cash', 'San Quentin (Live)'],
		// ['David Bowie', 'The Man Who Sold The World'],
		// ['Michael Kiwanuka', 'Home Again'],
		// ['Michael Jackson', 'The Way You Make Me Feel'],
		// ['Coldplay', 'Talk'],
		// ['Golden Earring', 'I Cant Sleep Without You (Naked)'],
		// ['Hans de Booij', 'Annabel'],
		// ['Normaal', 'Alie'],
		// ['Etta James', 'Id Rather Go Blind'],
		// ['Janis Ian', 'At Seventeen'],
		// ['Ralph McTell', 'Streets Of London'],
		// ['Paul McCartney  Wings', 'Mull Of Kintyre'],
		// ['Elvis Presley', 'An American Trilogy'],
		// ['U2', 'Ordinary Love'],
		// ['Fleetwood Mac', 'You Make Lovin Fun'],
		// ['The Smiths', 'How Soon Is Now?'],
		// ['Metallica', 'Memory Remains'],
		// ['Eminem  Rihanna', 'The Monster'],
		// ['Kane', 'Damn Those Eyes'],
		// ['Queen', 'Spread Your Wings'],
		// ['Olivia Rodrigo', 'Good 4 U'],
		// ['ABBA', 'The Name Of The Game '],
		// ['Bruce Springsteen', 'No Surrender'],
		// ['Thin Lizzy', 'The Boys Are Back In Town'],
		// ['Bruno Mars', 'Locked Out Of Heaven'],
		// ['Coldplay', 'Every Teardrop Is A Waterfall'],
		// ['Kraftwerk', 'Autobahn'],
		// ['Tracy Chapman', 'Talkin Bout A Revolution'],
		// ['3 Doors Down', 'Here Without You'],
		// ['Alphaville', 'Big In Japan'],
		// ['Sam Cooke', 'A Change Is Gonna Come'],
		// ['Anouk', 'R U Kiddin Me'],
		// ['Stevie Wonder', 'Isnt She Lovely'],
		// ['Bee Gees', 'Nights On Broadway'],
		// ['Seal', 'Crazy'],
		// ['Fleetwood Mac', 'Big Love'],
		// ['BLØF', 'Zaterdag'],
		// ['André Hazes', 'Het Laatste Rondje'],
		// ['The Prodigy', 'Breathe'],
		// ['Mike  The Mechanics', 'The Living Years'],
		// ['Whitney Houston', 'I Have Nothing'],
		// ['Crowded House', 'Weather With You'],
		// ['Robert Plant', 'Big Log'],
		// ['Marco Borsato', 'Ik Leef Niet Meer Voor Jou'],
		// ['Porcupine Tree', 'Arriving Somewhere But Not Here'],
		// ['David Bowie', 'Ziggy Stardust'],
		// ['Bruce Springsteen', 'Hungry Heart'],
		// ['Beyoncé', 'Love On Top'],
		// ['Lukas Graham', '7 Years'],
		// ['Janis Joplin', 'Mercedes Benz'],
		// ['Julio Iglesias', 'Quiero'],
		// ['Katie Melua', 'Nine Million Bicycles'],
		// ['Paolo Conte', 'Max'],
		// ['Tom Jones', 'Green Green Grass Of Home'],
		// ['Outfield', 'Your Love'],
		// ['Genesis', 'Home By The Sea'],
		// ['George Harrison', 'My Sweet Lord'],
		// ['Mark Knopfler', 'Going Home: Theme Of The Local Hero'],
		// ['Stevie Ray Vaughan', 'Pride And Joy'],
		// ['The Cure', 'Lovesong'],
		// ['Orchestral Manoeuvres In The Dark', 'Enola Gay'],
		// ['Marco Borsato', 'Zij'],
		// ['OneRepublic', 'Counting Stars'],
		// ['Conan Gray', 'Astronomy'],
		// ['Electric Light Orchestra', 'Dont Bring Me Down'],
		// ['Gorki', 'Mia'],
		// ['Guns N Roses', 'Live And Let Die'],
		// ['The Fray', 'How To Save A Life'],
		// ['Is Ook Schitterend', 'Voltooid Verleden Tijd'],
		// ['Michael Jackson', 'Dont Stop Til You Get Enough '],
		// ['George Michael', 'One More Try'],
		// ['Red Hot Chili Peppers', 'By The Way'],
		// ['Robbie Williams', 'Shes The One'],
		// ['Michael Jackson', 'Human Nature'],
		// ['The The', 'Uncertain Smile'],
		// ['Guus Meeuwis', 't Dondert En t Bliksemt'],
		// ['Elton John', 'Can You Feel The Love Tonight'],
		// ['The Babys', 'Everytime I Think Of You'],
		// ['Spider Murphy Gang', 'Skandal Im Sperrbezirk'],
		// ['R.E.M.', 'Shiny Happy People'],
		// ['Flemming', 'Paracetamollen'],
		// ['Vandenberg', 'Burning Heart'],
		// ['Bee Gees', 'I Started A Joke'],
		// ['Elbow', 'Magnificent (She Says)'],
		// ['The Hollies', 'He Aint Heavy, Hes My Brother'],
		// ['Simon  Garfunkel', 'Cecilia'],
		// ['André Hazes', 'n Vriend'],
		// ['Tiësto', 'Adagio For Strings'],
		// ['Bee Gees', 'To Love Somebody'],
		// ['Blondie', 'Heart Of Glass'],
		// ['Bob Marley  The Wailers', 'Stir It Up (Live)'],
		// ['Alderliefste  Paul de Leeuw', 'Une Belle Histoire/Een Mooi Verhaal'],
		// ['Barry Ryan', 'Eloise'],
		// ['Robbie Williams', 'Come Undone'],
		// ['The Temper Trap', 'Sweet Disposition'],
		// ['Nick Cave  The Bad Seeds', 'Red Right Hand'],
		// ['R.E.M.', 'The One I Love'],
		// ['BLØF', 'Aanzoek Zonder Ringen'],
		// ['Adele', 'Water Under The Bridge'],
		// ['Lewis Capaldi', 'Forget Me'],
		// ['Robert Long', 'Kalverliefde'],
		// ['Michael Andrews ft. Gary Jules', 'Mad World'],
		// ['Alice In Chains', 'Rooster'],
		// ['Stevie Wonder', 'I Wish'],
		// ['Ilse DeLange', 'Im Not So Tough'],
		// ['Earth  Fire', 'Memories'],
		// ['Lenny Kravitz', 'Are You Gonna Go My Way?'],
		// ['The Rolling Stones', 'Angry'],
		// ['Stevie Nicks', 'Edge Of Seventeen'],
		// ['Meau ft. Racoon', 'Dans Mn Ogen Dicht'],
		// ['Led Zeppelin', 'Dazed And Confused'],
		// ['Fleetwood Mac', 'Never Going Back Again'],
		// ['Céline Dion  Barbra Streisand', 'Tell Him'],
		// ['André Hazes', 'Ik Meen t'],
		// ['S10', 'Adem Je In'],
		// ['Sugarhill Gang', 'Rappers Delight'],
		// ['Michael Bublé', 'Feeling Good'],
		// ['Bob Dylan', 'Knockin On Heavens Door'],
		// ['Justin Timberlake', 'Mirrors'],
		// ['Boney M.', 'Rasputin'],
		// ['Golden Earring', 'Weekend Love'],
		// ['George Michael', 'You Have Been Loved'],
		// ['Foo Fighters', 'All My Life'],
		// ['Bruce Hornsby  The Range', 'The Way It Is'],
		// ['Simply Red', 'Stars'],
		// ['Kane', 'No Surrender'],
		// ['Queen', 'You Dont Fool Me'],
		// ['The Prodigy', 'No Good (Start The Dance)'],
		// ['Bruce Springsteen', 'Human Touch'],
		// ['Eva Cassidy', 'Songbird'],
		// ['Frank Boeijen Groep', 'Hier Komt De Storm'],
		// ['Whitney Houston', 'Greatest Love Of All'],
		// ['Rod Stewart', 'Maggie May'],
		// ['Beyoncé  Jay-Z', 'Crazy In Love'],
		// ['Armand', 'Ben Ik Te Min'],
		// ['Robert Cray Band', 'Right Next Door (Because Of Me)'],
		// ['Tom Petty  The Heartbreakers', 'Mary Janes Last Dance'],
		// ['Peter Gabriel', 'In Your Eyes '],
		// ['André Hazes', 'Het Is Koud Zonder Jou'],
		// ['Snelle', 'Reünie'],
		// ['Patrick Hernandez', 'Born To Be Alive'],
		// ['Youssou NDour  Neneh Cherry', '7 Seconds'],
		// ['Imagine Dragons', 'Enemy'],
		// ['Owl City', 'Fireflies'],
		// ['Jean Michel Jarre', 'Oxygene IV'],
		// ['Smash Mouth', 'All Star'],
		// ['Suzan  Freek', 'Honderd Keer'],
		// ['Creedence Clearwater Revival', 'Down On The Corner'],
		// ['Joe Cocker', 'You Can Leave Your Hat On'],
		// ['Coldplay', 'In My Place'],
		// ['The Hollies', 'The Air That I Breathe'],
		// ['Roy Orbison', 'In Dreams'],
		// ['KISS', 'Sure Know Something'],
		// ['Marvin Gaye', 'Sexual Healing'],
		// ['Stealers Wheel', 'Stuck In The Middle With You'],
		// ['Billy Joel', 'New York State Of Mind'],
		// ['Anouk', 'Jerusalem'],
		// ['Suzan  Freek', 'Weg Van Jou'],
		// ['The National', 'Bloodbuzz Ohio'],
		// ['Coldplay', 'Charlie Brown'],
		// ['Nits', 'Nescio'],
		// ['Goldband', 'De Langste Nacht'],
		// ['Whitney Houston', 'One Moment In Time'],
		// ['The Beatles', 'I Am The Walrus'],
		// ['Teddy Swims', 'Lose Control'],
		// ['Creedence Clearwater Revival', 'Born On The Bayou'],
		// ['Steve Harley  Cockney Rebel', 'Make Me Smile (Come Up And See Me)'],
		// ['André Hazes', 'Uit Mn Bol'],
		// ['The Black Crowes', 'Remedy'],
		// ['Johnny Cash', 'A Thing Called Love'],
		// ['U2  Green Day', 'The Saints Are Coming'],
		// ['Dan Hartman', 'Relight My Fire'],
		// ['Imagine Dragons', 'Bad Liar'],
		// ['Madonna', 'Vogue'],
		// ['Tom Petty  The Heartbreakers', 'Learning To Fly'],
		// ['Danny Vera', 'The Devils Son'],
		// ['Arctic Monkeys', 'Snap Out Of It'],
		// ['Smashing Pumpkins', 'Bullet With Butterfly Wings'],
		// ['Imagine Dragons', 'On Top Of The World'],
		// ['Nielson', 'IJskoud'],
		// ['The Beatles', 'When Im Sixty-Four'],
		// ['ABBA', 'Summer Night City'],
		// ['Jimi Hendrix', 'Purple Haze'],
		// ['OutKast', 'Hey Ya!'],
		// ['Dotan', 'Home'],
		// ['Norah Jones', 'Sunrise'],
		// ['Suzan  Freek', 'Onderweg Naar Later'],
		// ['Bob Marley  The Wailers', 'Is This Love'],
		// ['Pulp', 'Common People'],
		// ['Stevie Wonder', 'Sir Duke'],
		// ['Extreme', 'More Than Words'],
		// ['Elton John', 'Sorry Seems To Be The Hardest Word'],
		// ['Diggy Dex  Vali', 'La Vie Est Belle'],
		// ['One Direction', 'One Way Or Another (Teenage Kicks)'],
		// ['ABBA', 'Dont Shut Me Down'],
		// ['Sting  Cheb Mami', 'Desert Rose'],
		// ['Yes', 'Close To The Edge '],
		// ['Cutting Crew', '(I Just Died) In Your Arms Tonight'],
		// ['Therapy?', 'Diane'],
		// ['Anouk', 'Three Days In A Row'],
		// ['Marvin Gaye', 'I Heard It Through The Grapevine'],
		// ['Toto', 'Home Of The Brave'],
		// ['House Of Pain', 'Jump Around'],
		// ['James Taylor', 'Youve Got A Friend'],
		// ['Nick  Simon', 'De Soldaat'],
		// ['Tears For Fears', 'Head Over Heels'],
		// ['S10  BLØF', 'Laat Me Los'],
		// ['Bill Withers  Grover Washington, Jr.', 'Just The Two Of Us'],
		// ['The Rolling Stones', 'As Tears Go By'],
		// ['Frank Sinatra', 'Theme From New York, New York'],
		// ['Bon Jovi', 'In These Arms'],
		// ['The Cats', 'Times Were When'],
		// ['Snow Patrol', 'Shut Your Eyes'],
		// ['Michael Jackson', 'Bad'],
		// ['Bruno Mars', 'Grenade'],
		// ['Patti Smith Group', 'Because The Night'],
		// ['MGMT', 'Kids'],
		// ['America', 'Ventura Highway'],
		// ['Neil Diamond', 'Love On The Rocks'],
		// ['Pet Shop Boys', 'West End Girls '],
		// ['Madonna', 'La Isla Bonita'],
		// ['Japan', 'Nightporter '],
		// ['Meat Loaf', 'For Crying Out Loud '],
		// ['Scott McKenzie', 'San Francisco (Be Sure To Wear Flowers In Your Hair)'],
		// ['Cranberries', 'Dreams'],
		// ['Fleetwood Mac', 'Gypsy'],
		// ['Chic', 'Le Freak'],
		// ['Beastie Boys', 'Fight For Your Right (To Party)'],
		// ['Roger Glover  Guests', 'Love Is All'],
		// ['John Denver', 'Thank God Im A Country Boy'],
		// ['Bruce Springsteen', 'Racing In The Street'],
		// ['LP', 'Lost On You'],
		// ['Chris Rea', 'Josephine'],
		// ['Floor Jansen', 'Fire'],
		// ['Jenny Arean  Frans Halsema', 'Vluchten Kan Niet Meer'],
		// ['Amy Winehouse', 'Love Is A Losing Game'],
		// ['The Beatles', 'Yellow Submarine'],
		// ['Imagine Dragons', 'Bones'],
		// ['Ed Sheeran', 'Overpass Graffiti'],
		// ['The Rolling Stones', 'Lady Jane'],
		// ['Guano Apes', 'Open Your Eyes'],
		// ['Bee Gees', 'Spicks And Specks'],
		// ['Supertramp', 'Hide In Your Shell'],
		// ['Youp van t Hek', 'Flappie'],
		// ['Jamiroquai', 'Virtual Insanity'],
		// ['Ramses Shaffy', 'Sammy'],
		// ['Ben Howard', 'Keep Your Head Up'],
		// ['Willie Nelson', 'Always On My Mind'],
		// ['Backstreet Boys', 'Everybody (Backstreets Back)'],
		// ['Dolly Dots', 'Love Me Just A Little Bit More (Totally Hooked On You)'],
		// ['Gilbert Bécaud', 'Nathalie'],
		// ['P!nk', 'Dear Mr. President'],
		// ['Amanda Marshall', 'Beautiful Goodbye'],
		// ['Delerium ft. Sarah McLachlan', 'Silence (Tiësto Mix)'],
		// ['Adele', 'Rumour Has It'],
		// ['Avicii', 'Addicted To You'],
		// ['Jacques Brel', 'Mijn Vlakke Land'],
		// ['Talk Talk', 'Living In Another World'],
		// ['Guns N Roses', 'You Could Be Mine'],
		// ['The Weeknd ft. Daft Punk', 'I Feel It Coming'],
		// ['The Alan Parsons Project', 'Dont Answer Me'],
		// ['Ph.D.', 'I Wont Let You Down'],
		// ['Douwe Bob  Jacqueline Govaert', 'I Do'],
		// ['Racoon', 'Shoes Of Lightning'],
		// ['Jeff Wayne  Justin Hayward', 'Forever Autumn'],
		// ['Yes', 'Roundabout '],
		// ['Electric Light Orchestra', 'Livin Thing'],
		// ['Brainbox', 'Summertime'],
		// ['Foreigner', 'Cold As Ice'],
		// ['Nirvana', 'Something In The Way'],
		// ['Paul de Leeuw', 'Vlieg Met Me Mee (Live)'],
		// ['DI-RECT', '90s Kid'],
		// ['Nick  Simon', 'Kijk Omhoog'],
		// ['Oasis', 'Live Forever'],
		// ['Walk The Moon', 'Shut Up And Dance'],
		// ['Offspring', 'Pretty Fly (For A White Guy)'],
		// ['Elvis Presley', 'Return To Sender'],
		// ['Herman Brood  Henny Vrienten', 'Als Je Wint'],
		// ['Eric Clapton', 'Cocaine'],
		// ['The Black Keys', 'Gold On The Ceiling'],
		// ['Bee Gees', 'You Win Again'],
		// ['Twarres', 'Wêr Bisto'],
		// ['Cyndi Lauper', 'Time After Time'],
		// ['Creedence Clearwater Revival', 'Lookin Out My Back Door'],
		// ['Creed', 'With Arms Wide Open'],
		// ['Billie Eilish', 'What Was I Made For?'],
		// ['UB40', 'Food For Thought'],
		// ['Marvin Gaye  Tammi Terrell', 'Aint No Mountain High Enough'],
		// ['Run DMC  Aerosmith', 'Walk This Way'],
		// ['Notorious B.I.G.', 'Hypnotize'],
		// ['Editors', 'An End Has A Start'],
		// ['Weather Girls', 'Its Raining Men'],
		// ['Boney M.', 'Rivers Of Babylon'],
		// ['Rihanna', 'Diamonds'],
		// ['James Taylor', 'Fire And Rain'],
		// ['Golden Earring', 'Hold Me Now'],
		// ['The Buoys', 'Give Up Your Guns'],
		// ['Herman Berkien', 'Utereg Me Stadje'],
		// ['Dido', 'White Flag'],
		// ['Alan Walker', 'Faded'],
		// ['AC/DC', 'Its A Long Way To The Top (If You Wanna Rock N Roll)'],
		// ['Green Day', 'Jesus Of Suburbia'],
		// ['Kensington', 'Bridges'],
		// ['Earth  Fire', 'Weekend'],
		// ['Kensington', 'All For Nothing'],
		// ['Florence + The Machine', 'Youve Got The Love'],
		// ['Chris Stapleton', 'Cold'],
		// ['Of Monsters And Men', 'Little Talks'],
		// ['Queen', 'Save Me'],
		// ['Ilse DeLange', 'World Of Hurt'],
		// ['The Moody Blues', 'Tuesday Afternoon'],
		// ['Mika', 'Grace Kelly'],
		// ['R.E.M.', 'Its The End Of The World As We Know It'],
		// ['James Blunt', 'Goodbye My Lover'],
		// ['The Smiths', 'This Charming Man'],
		// ['Bökkers', 'Kold Bloed'],
		// ['The Beach Boys', 'Sloop John B'],
		// ['P!nk', 'Family Portrait'],
		// ['Tears For Fears', 'Mad World'],
		// ['Rondé', 'Love Myself'],
		// ['Coldplay  Buena Vista Social Club', 'Clocks (Rhythms Del Mundo)'],
		// ['The Who', 'Wont Get Fooled Again '],
		// ['Wildstylez ft. Niels Geusebroek', 'Year Of Summer'],
		// ['Van Morrison', 'Moondance'],
		// ['Ed Sheeran', 'Afterglow'],
		// ['Bruno Mars', '24K Magic'],
		// ['Ilse DeLange', 'So Incredible'],
		// ['Fats Domino', 'Blueberry Hill'],
		// ['Elvis Presley', 'Guitar Man'],
		// ['The Doors', 'Love Her Madly'],
		// ['Elton John', 'Daniel'],
		// ['Anouk  Douwe Bob', 'Hold Me'],
		// ['The Beatles', 'Shes Leaving Home'],
		// ['Martin Garrix', 'Animals'],
		// ['Frank Ocean', 'Lost'],
		// ['Paul McCartney  Frog Chorus', 'We All Stand Together'],
		// ['Live', 'Run To The Water'],
		// ['Stereophonics', 'Maybe Tomorrow'],
		// ['Robin S', 'Show Me Love'],
		// ['Frankie Goes To Hollywood', 'Relax'],
		// ['Maarten van Roozendaal', 'Red Mij Niet'],
		// ['Elvis Presley', 'Blue Suede Shoes'],
		// ['Alain Clark', 'Father  Friend'],
		// ['Rowwen Hèze', 'T Roeie Klied'],
		// ['Michael Jackson', 'Stranger In Moscow'],
		// ['Bill Medley  Jennifer Warnes', '(Ive Had) The Time Of My Life'],
		// ['Ultravox', 'Dancing With Tears In My Eyes'],
		// ['Roy Orbison', 'Oh, Pretty Woman'],
		// ['Doobie Brothers', 'What A Fool Believes'],
		// ['Editors', 'The Racing Rats'],
		// ['DI-RECT', 'Devil Dont Care'],
		// ['The Prodigy', 'Out Of Space'],
		// ['Status Quo', 'In The Army Now'],
		// ['De Dijk', 'Mijn Van Straat Geredde Roos'],
		// ['Van Halen', 'Why Cant This Be Love'],
		// ['Nina Simone', 'My Baby Just Cares For Me'],
		// ['Boudewijn de Groot', 'Een Meisje Van 16'],
		// ['Elvis Presley', 'Are You Lonesome Tonight?'],
		// ['The Smiths', 'Heaven Knows Im Miserable Now'],
		// ['Vance Joy', 'Riptide'],
		// ['Snelle', 'In Mn Bloed'],
		// ['Ronan Keating', 'When You Say Nothing At All'],
		// ['DI-RECT', 'How My Heart Was Won'],
		// ['Coldplay', 'Green Eyes'],
		// ['Queens Of The Stone Age', 'I Sat By The Ocean'],
		// ['Otis Redding', 'Ive Got Dreams To Remember'],
		// ['Labi Siffre', '(Something Inside) So Strong'],
		// ['Tanita Tikaram', 'Twist In My Sobriety'],
		// ['The National', 'I Need My Girl'],
		// ['Jonathan Jeremiah', 'Happiness'],
		// ['Lionel Richie', 'All Night Long (All Night)'],
		// ['De Kast', 'Hart Van Mijn Gevoel'],
		// ['Robbie Williams', 'The Road To Mandalay'],
		// ['Ten Years After', 'Im Going Home'],
		// ['Chicago', '25 Or 6 To 4'],
		// ['The Monkees', 'Im A Believer'],
		// ['Bee Gees', 'You Should Be Dancing'],
		// ['Sex Pistols', 'God Save The Queen'],
		// ['Snollebollekes', 'Links Rechts'],
		// ['U2', 'Stuck In A Moment You Cant Get Out Of'],
		// ['Dire Straits', 'Water Of Love'],
		// ['Eurythmics', 'There Must Be An Angel (Playing With My Heart)'],
		// ['Pearl Jam', 'Rearviewmirror'],
		// ['Avicii', 'Waiting For Love'],
		// ['Queen', 'Made In Heaven'],
		// ['Jefferson Airplane', 'Somebody To Love'],
		// ['Roxy Music', 'More Than This'],
		// ['Bonnie Raitt', 'I Cant Make You Love Me'],
		// ['Leonard Cohen', 'Famous Blue Raincoat'],
		// ['Deep Purple', 'Black Night'],
		// ['U2', 'City Of Blinding Lights'],
		// ['Billy Joel', 'Uptown Girl'],
		// ['Paul Simon', 'Homeless'],
		// ['Niall Horan', 'Slow Hands'],
		// ['Cyndi Lauper', 'Girls Just Want To Have Fun'],
		// ['Crash Test Dummies', 'Mmm Mmm Mmm Mmm'],
		// ['Suzanne Vega', 'Luka'],
		// ['De Dijk', 'Laat Het Vanavond Gebeuren'],
		// ['The Hollies', 'Long Cool Woman (In A Black Dress)'],
		// ['Armin van Buuren', 'Blah Blah Blah'],
		// ['Grace Jones', 'La Vie En Rose'],
		// ['Led Zeppelin', 'Black Dog'],
		// ['Queen', 'Heaven For Everyone'],
		// ['Johan', 'Tumble And Fall'],
		// ['Sting', 'Moon Over Bourbon Street'],
		// ['Damien Rice', 'The Blowers Daughter'],
		// ['Ed Sheeran', 'Galway Girl'],
		// ['Van Morrison', 'Into The Mystic'],
		// ['The Who', 'Overture (Tommy)'],
		// ['KISS', 'Detroit Rock City'],
		// ['P!nk', 'Never Gonna Not Dance Again'],
		// ['Golden Earrings', 'Sound Of The Screaming Day'],
		// ['Taylor Swift', 'Cruel Summer'],
		// ['Imagine Dragons', 'Sharks'],
		// ['Shania Twain', 'Man! I Feel Like A Woman'],
		// ['Son Mieux', 'This Is The Moment'],
		// ['ChefSpecial', 'Nicotine'],
		// ['Elvis Presley vs. Junkie XL', 'A Little Less Conversation'],
		// ['Santana', 'Europa (Earths Cry Heavens Smile)'],
		// ['Genesis', 'Invisible Touch'],
		// ['Van Halen', 'Panama'],
		// ['Ramses Shaffy', 'Wij Zullen Doorgaan'],
		// ['Reinhard Mey', 'Gute Nacht Freunde'],
		// ['Dire Straits', 'Calling Elvis'],
		// ['The Rolling Stones', 'Midnight Rambler'],
		// ['Green Day', 'When I Come Around'],
		// ['Ramones', 'Blitzkrieg Bop'],
		// ['Guus Meeuwis', 'Proosten'],
		// ['U2', 'Vertigo'],
		// ['Wham!', 'Everything She Wants'],
		// ['Roxy Music', 'Love Is The Drug'],
		// ['Kings Of Leon', 'Pyro'],
		// ['Rondé', 'Bright Eyes'],
		// ['Herman Brood  His Wild Romance', 'I Love You Like I Love Myself'],
		// ['Michael Jackson', 'Off The Wall'],
		// ['Karin Bloemen', 'Geen Kind Meer'],
		// ['Stereophonics', 'Dakota'],
		// ['Michael Jackson', 'Will You Be There'],
		// ['Herbert Grönemeyer', 'Mensch'],
		// ['U2', 'Gloria (Live)'],
		// ['Within Temptation', 'Memories'],
		// ['UB40  Chrissie Hynde', 'I Got You Babe'],
		// ['Traveling Wilburys', 'Handle With Care'],
		// ['The Verve', 'The Drugs Dont Work'],
		// ['Acda  De Munnik', 'Morgen Wordt Fantastisch'],
		// ['Creedence Clearwater Revival', 'Up Around The Bend'],
		// ['Acda  De Munnik', 'Mooi Liedje'],
		// ['Shadows', 'Apache'],
		// ['Typhoon', 'Hemel Valt'],
		// ['Doe Maar', '1 Nacht Alleen'],
		// ['Bob Marley  The Wailers', 'One Love/People Get Ready'],
		// ['The Police', 'Dont Stand So Close To Me'],
		// ['Blaudzun', 'Promises Of No Mans Land'],
		// ['Herman Brood  His Wild Romance', 'Still Believe'],
		// ['The Beatles', 'Dont Let Me Down'],
		// ['Prince', 'The Cross'],
		// ['Ella Fitzgerald  Louis Armstrong', 'Summertime'],
		// ['Toto', 'Ill Be Over You'],
		// ['Eurythmics', 'Here Comes The Rain Again'],
		// ['Supertramp', 'Its Raining Again'],
		// ['Smashing Pumpkins', 'Tonight, Tonight'],
		// ['Mud', 'Dynamite'],
		// ['Solomon Burke  De Dijk', 'Hold On Tight'],
		// ['Bruno Mars', 'Just The Way You Are'],
		// ['BLØF', 'Later Als Ik Groter Ben'],
		// ['Steve Miller Band', 'Fly Like An Eagle'],
		// ['Frankie Goes To Hollywood', 'Two Tribes'],
		// ['Clouseau', 'Domino'],
		// ['Lorde', 'Royals'],
		// ['David Bowie', 'Blackstar'],
		// ['Ed Sheeran  Elton John', 'Merry Christmas'],
		// ['Stef Bos', 'Ik Heb Je Lief'],
		// ['George Ezra', 'Budapest'],
		// ['OutKast', 'Ms. Jackson'],
		// ['Golden Earring', 'The Devil Made Me Do It'],
		// ['Black', 'Wonderful Life'],
		// ['Paul McCartney  Wings', 'Live And Let Die'],
		// ['Muse', 'Sing For Absolution'],
		// ['Peter Frampton', 'Show Me The Way (Albumversie Live)'],
		// ['Q65', 'The Life I Live'],
		// ['Swedish House Mafia ft. John Martin', 'Dont You Worry Child'],
		// ['Carpenters', '(They Long To Be) Close To You'],
		// ['Billy Ocean', 'Love Really Hurts Without You'],
		// ['Muse', 'Feeling Good'],
		// ['Jeff Buckley', 'Lover, You Shouldve Come Over'],
		// ['The Pointer Sisters', 'Fire'],
		// ['Tröckener Kecks', 'Met Hart En Ziel'],
		// ['The Who', 'See Me, Feel Me'],
		// ['Chris Isaak', 'Blue Hotel'],
		// ['Gary Moore  Phil Lynott', 'Out In The Fields'],
		// ['The Rolling Stones', 'Under My Thumb'],
		// ['Danny Vera', 'The Weight'],
		// ['Boudewijn de Groot', 'Prikkebeen'],
		// ['Doobie Brothers', 'Long Train Runnin'],
		// ['André van Duin', 'Als De Zon Schijnt'],
		// ['Van Dik Hout', 'Meer Dan Een Ander'],
		// ['John Mayer', 'Waiting On The World To Change'],
		// ['The B-52s', 'Love Shack'],
		// ['David Bowie', 'Fame'],
		// ['Bruce Springsteen', 'Brilliant Disguise'],
		// ['Coldplay', 'Politik'],
		// ['B.B. King', 'The Thrill Is Gone'],
		// ['The Script', 'Breakeven'],
		// ['Drukwerk', 'Je Loog Tegen Mij'],
		// ['Doe Maar', 'Tijd Genoeg'],
		// ['Muddy Waters', 'Mannish Boy'],
		// ['Mumford  Sons', 'Hopeless Wanderer'],
		// ['George Ezra', 'Green Green Grass'],
		// ['Mr. Probz', 'Waves'],
		// ['Boston', 'Dont Look Back'],
		// ['Frank Boeijen Groep', 'Winter In Hamburg'],
		// ['Simply Red', 'Fairground'],
		// ['Whitesnake', 'Is This Love'],
		// ['Billy Idol', 'Eyes Without A Face'],
		// ['Wheatus', 'Teenage Dirtbag'],
		// ['Queen', 'One Vision '],
		// ['Ed Sheeran', 'Celestial'],
		// ['INXS', 'Need You Tonight'],
		// ['Deep Purple', 'Woman From Tokyo'],
		// ['Phil Collins', 'Take Me Home'],
		// ['J.J. Cale', 'Call Me The Breeze'],
		// ['J.J. Cale', 'After Midnight'],
		// ['Eagles', 'Take It To The Limit'],
		// ['Foreigner', 'That Was Yesterday'],
		// ['Gossip', 'Heavy Cross'],
		// ['The Kinks', 'Waterloo Sunset'],
		// ['Kensington', 'Home Again'],
		// ['Golden Earrings', 'Ive Just Lost Somebody'],
		// ['George Michael', 'Kissing A Fool'],
		// ['The Pogues', 'Fiesta'],
		// ['Birdy', 'Skinny Love'],
		// ['Alanis Morissette', 'Thank U'],
		// ['The Babys', 'Isnt It Time?'],
		// ['Foster The People', 'Pumped Up Kicks'],
		// ['The Black Crowes', 'Hard To Handle'],
		// ['Barbra Streisand', 'The Way We Were'],
		// ['Nirvana', 'Polly'],
		// ['Plain White Ts', 'Hey There Delilah'],
		// ['Nina Hagen', 'Unbeschreiblich Weiblich'],
		// ['Snelle', 'Smoorverliefd'],
		// ['Ellen Foley', 'We Belong To The Night'],
		// ['Womack  Womack', 'Teardrops'],
		// ['Genesis', 'No Son Of Mine'],
		// ['Joe Cocker  Jennifer Warnes', 'Up Where We Belong'],
		// ['The Rolling Stones', 'Beast Of Burden'],
		// ['Thomas Acda, Kraantje Pappie  Rolf Sanchez', 'Missen Zou'],
		// ['Shirley Bassey', 'This Is My Life'],
		// ['Prince', 'Gold'],
		// ['J.J. Cale', 'Cocaine'],
		// ['Paul Simon', 'Late In The Evening'],
		// ['Henk Wijngaard', 'Met De Vlam In De Pijp'],
		// ['Crowded House', 'Into Temptation'],
		// ['Counting Crows', 'Accidentally In Love'],
		// ['Diesel', 'Sausolito Summernight'],
		// ['Rod Stewart', 'I Dont Want To Talk About It'],
		// ['Bruce Springsteen', 'Secret Garden'],
		// ['Beyoncé', 'Single Ladies (Put A Ring On It)'],
		// ['Mumford  Sons', 'Lover Of The Light'],
		// ['Steely Dan', 'Do It Again'],
		// ['Vitesse', 'Rosalyn'],
		// ['Metejoor  Hannah Mae', 'Wat Wil Je Van Mij'],
		// ['Wolfmother', 'Woman'],
		// ['Stevie Wonder', 'Master Blaster (Jammin)'],
		// ['Neil Young', 'Harvest'],
		// ['Radiohead', 'High And Dry'],
		// ['Caro Emerald', 'A Night Like This'],
		// ['Don Henley', 'New York Minute']
	];

	const [theText, setTheText] = useState('');

	const findLyrics = async (artist, title) => {
		try {
	        let lyrics = await lyricsAuth.searchLyrics(artist, title);
	       	const cleanLyrics = lyrics.replace(/\n/g, ' ').toUpperCase().replace(/[^ aeiouyAEIOUY]/g, '').replace('  ', ' ').replace(/\s+/g, ' ');

	        const foundPatterns = [];
	        // console.log(originalLyrics);
			for (let i = 0; i < patterns.length; i++)
			{
				if (cleanLyrics.indexOf(patterns[i]) > -1)
				{
					foundPatterns.push(patterns[i]);

					console.log('Found pattern in "' + artist + ' - ' + title + '": ' + patterns[i]);
				}
			}

			if (foundPatterns.length === 0)
			{
				// console.log('Lyrics of "' + artist + ' - ' + title + '" found but no pattern');
			}

	    } catch (error) {
	        // console.log('Lyrics of "' + artist + ' - ' + title + '" not found');
	    }
	};

	const findPatterns = (inputSongText) => {
		const foundPatterns = [];

		for (let i = 0; i < patterns.length; i++)
		{
			if (inputSongText.indexOf(patterns[i]) > -1)
			{
				foundPatterns.push(patterns[i]);
			}
		}

		return foundPatterns;
	};

	const findPatternsNoSpaces = (inputSongText) => {
		const textNoSpaces = inputSongText.replace(/\s+/g, '');
		const foundPatterns = [];

		for (let i = 0; i < patternsNoSpaces.length; i++)
		{
			if (textNoSpaces.indexOf(patternsNoSpaces[i]) > -1)
			{
				foundPatterns.push(patternsNoSpaces[i]);
			}
		}

		return foundPatterns;
	};

	const findPatternFromLyrics = async (artist, title) => {
		const songText = findLyrics(artist, title).then(x => { 
		    return x;
		});
		const converted = inputText(songText);

		console.log(songText);
		return songText;
	};

	const inputText = (input) => {
		const noEnters = input.replace(/\n/g, ' ');
		const uppercase = noEnters.toUpperCase();
		const removedCons = uppercase.replace(/[^ aeiouyAEIOUY]/g, '');
		setTheText(removedCons);
	};

	// for (let i = 0; i < songs.length; i++)
	// {
	// 	findLyrics(songs[i][0], songs[i][1]);
	// }

	return (
		<Container>
			<Row>
				<Col>
					<Table>
						<thead>
							<tr>
								<th>Artiest</th>
								<th>Titel</th>
								<th>Patroon</th>
							</tr>
						</thead>
						<tbody>
							{
								// songs.map((song, index) => (
								// 	<tr key={index}>
								// 		<td>{song[0]}</td>
								// 		<td>{song[1]}</td>
								// 		<td>{}</td>
								// 	</tr>
								// ))
							}
						</tbody>
					</Table>
				</Col>
			</Row>
			<Row>
				<Col>
					<br/>
					<h5>Gevonden patronen:</h5>
					<ul>{
						findPatterns(theText).map((pattern, index) => (
							<li key={index}>{pattern}</li>
						))
					}</ul>
				</Col>
			</Row>
			<Row>
				<Col>
					<h5>Gevonden patronen, witruimte verwijderd:</h5>
					<ul>{
						findPatternsNoSpaces(theText).map((pattern, index) => (
							<li key={index}>{pattern}</li>
						))
					}</ul>
				</Col>
			</Row>
			<Row>
				<Col>
					<hr/>
					<h5>Songtekst plakken:</h5>
					<Form.Control as="textarea" rows={15} onChange={(e) => inputText(e.target.value)} onPaste={(e) => inputText(e.target.value)} />
				</Col>
			</Row>
		</Container>
	);
}

export default Opgave8;